/**
 * Models barrel export - All Appetite entities
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appetite
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./appetite-binding.entity.js";
export * from "./appetite-criterium.entity.js";
