/**
 * ListAlgorithmVariations handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listAlgorithmVariations } from "@appetitebind/api-server/domains/governance/handlers";
import type { GovernanceDDDDependencies } from "@appetitebind/api-server/domains/governance";
import { createVariation as createVariationEntity } from "@appetitebind/factories/governance";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@appetitebind/tests/shared";
import { GOVERNANCE_USE_CASES } from "../__factories__/use-cases.js";

describe("ListAlgorithmVariations", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: GovernanceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<GovernanceDDDDependencies>(
      GOVERNANCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createVariationEntity({ orgId }),
      createVariationEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListAlgorithmVariations, "execute").mockResolvedValue(useCaseResult);

    await listAlgorithmVariations(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListAlgorithmVariations.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
