/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@appetitebind/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildAppetiteDomainModule,
  buildAssessmentsDomainModule,
  buildControlsDomainModule,
  buildFairnessDomainModule,
  buildGovernanceDomainModule,
  buildIdentityDomainModule,
  buildMonitoringDomainModule,
  buildPredictionsDomainModule,
  buildUsecasesDomainModule,
} from "../domains/index.js";
import type {
  AppetiteDomainModule,
  AssessmentsDomainModule,
  ControlsDomainModule,
  FairnessDomainModule,
  GovernanceDomainModule,
  IdentityDomainModule,
  MonitoringDomainModule,
  PredictionsDomainModule,
  UsecasesDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private appetiteModule: AppetiteDomainModule | null = null;
  private assessmentsModule: AssessmentsDomainModule | null = null;
  private controlsModule: ControlsDomainModule | null = null;
  private fairnessModule: FairnessDomainModule | null = null;
  private governanceModule: GovernanceDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private monitoringModule: MonitoringDomainModule | null = null;
  private predictionsModule: PredictionsDomainModule | null = null;
  private usecasesModule: UsecasesDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get appetite domain module
   */
  getAppetiteDependencies(): AppetiteDomainModule {
    if (!this.appetiteModule) {
      this.appetiteModule = buildAppetiteDomainModule(this.dynamoClient);
    }
    return this.appetiteModule;
  }

  /**
   * Get assessments domain module
   */
  getAssessmentsDependencies(): AssessmentsDomainModule {
    if (!this.assessmentsModule) {
      this.assessmentsModule = buildAssessmentsDomainModule(this.dynamoClient);
    }
    return this.assessmentsModule;
  }

  /**
   * Get controls domain module
   */
  getControlsDependencies(): ControlsDomainModule {
    if (!this.controlsModule) {
      this.controlsModule = buildControlsDomainModule(this.dynamoClient);
    }
    return this.controlsModule;
  }

  /**
   * Get fairness domain module
   */
  getFairnessDependencies(): FairnessDomainModule {
    if (!this.fairnessModule) {
      this.fairnessModule = buildFairnessDomainModule(this.dynamoClient);
    }
    return this.fairnessModule;
  }

  /**
   * Get governance domain module
   */
  getGovernanceDependencies(): GovernanceDomainModule {
    if (!this.governanceModule) {
      this.governanceModule = buildGovernanceDomainModule(this.dynamoClient);
    }
    return this.governanceModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get monitoring domain module
   */
  getMonitoringDependencies(): MonitoringDomainModule {
    if (!this.monitoringModule) {
      this.monitoringModule = buildMonitoringDomainModule(this.dynamoClient);
    }
    return this.monitoringModule;
  }

  /**
   * Get predictions domain module
   */
  getPredictionsDependencies(): PredictionsDomainModule {
    if (!this.predictionsModule) {
      this.predictionsModule = buildPredictionsDomainModule(this.dynamoClient);
    }
    return this.predictionsModule;
  }

  /**
   * Get usecases domain module
   */
  getUsecasesDependencies(): UsecasesDomainModule {
    if (!this.usecasesModule) {
      this.usecasesModule = buildUsecasesDomainModule(this.dynamoClient);
    }
    return this.usecasesModule;
  }

  clearAppetiteDependencies(): void { this.appetiteModule = null; }
  clearAssessmentsDependencies(): void { this.assessmentsModule = null; }
  clearControlsDependencies(): void { this.controlsModule = null; }
  clearFairnessDependencies(): void { this.fairnessModule = null; }
  clearGovernanceDependencies(): void { this.governanceModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearMonitoringDependencies(): void { this.monitoringModule = null; }
  clearPredictionsDependencies(): void { this.predictionsModule = null; }
  clearUsecasesDependencies(): void { this.usecasesModule = null; }

  getAppetiteDependenciesForRequest(): AppetiteDomainModule {
    return this.getAppetiteDependencies();
  }

  getAssessmentsDependenciesForRequest(): AssessmentsDomainModule {
    return this.getAssessmentsDependencies();
  }

  getControlsDependenciesForRequest(): ControlsDomainModule {
    return this.getControlsDependencies();
  }

  getFairnessDependenciesForRequest(): FairnessDomainModule {
    return this.getFairnessDependencies();
  }

  getGovernanceDependenciesForRequest(): GovernanceDomainModule {
    return this.getGovernanceDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getMonitoringDependenciesForRequest(): MonitoringDomainModule {
    return this.getMonitoringDependencies();
  }

  getPredictionsDependenciesForRequest(): PredictionsDomainModule {
    return this.getPredictionsDependencies();
  }

  getUsecasesDependenciesForRequest(): UsecasesDomainModule {
    return this.getUsecasesDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.appetiteModule = null;
    this.assessmentsModule = null;
    this.controlsModule = null;
    this.fairnessModule = null;
    this.governanceModule = null;
    this.identityModule = null;
    this.monitoringModule = null;
    this.predictionsModule = null;
    this.usecasesModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
