/**
 * AppetiteCriterium Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appetite
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AppetiteCriteriumEntity } from "@appetitebind/core/appetite/models/index.js";
import { appetiteSchemas } from "@appetitebind/core/appetite";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "apt";

export function createAppetiteCriterium(overrides: Partial<AppetiteCriteriumEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    criteriaId: overrides.criteriaId ?? `acr_${ulid().toLowerCase()}`,
    questions: overrides.questions ?? [],
    version: overrides.version ?? faker.lorem.word(),
    ...overrides,
  };

  return appetiteSchemas.AppetiteCriteria.parse(raw);
}

export function appetiteCriteriumBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAppetiteCriterium(overrides));
}
