/**
 * Assessments DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Assessments Domain Module - Composition root
 *
 * DDD: Composition root for assessments domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AssessmentRepositoryAdapter,
  ReferenceComparisonRepositoryAdapter,
  RiskIdentificationRepositoryAdapter,
  SignOffRepositoryAdapter,
} from "@appetitebind/adapters/assessments";
import { getIdGeneratorService } from "@appetitebind/adapters";
import type { AdapterDynamoDBClient } from "@appetitebind/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateRiskAssessment,
  ExecuteListRiskAssessments,
  ExecuteRecordReferenceComparison,
  ExecuteRecordRiskIdentification,
  ExecuteSignOffRiskAssessment,
} from "@appetitebind/services/assessments/usecases";
// Ports (interfaces)
import type {
  AssessmentRepository,
  ReferenceComparisonRepository,
  RiskIdentificationRepository,
  SignOffRepository,
} from "@appetitebind/services/assessments/ports";

export interface AssessmentsDomainModule {
  repos: {
    assessments: AssessmentRepository;
    referenceComparisons: ReferenceComparisonRepository;
    riskIdentifications: RiskIdentificationRepository;
    signOffs: SignOffRepository;
  };
  useCases: {
    assessments: {
      create: ExecuteCreateRiskAssessment;
      list: ExecuteListRiskAssessments;
    };
    referenceComparisons: {
      get: ExecuteRecordReferenceComparison;
    };
    riskIdentifications: {
      get: ExecuteRecordRiskIdentification;
    };
    signOffs: {
      get: ExecuteSignOffRiskAssessment;
    };
  };
}

export function buildAssessmentsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AssessmentsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      assessments?: AssessmentRepository;
      referenceComparisons?: ReferenceComparisonRepository;
      riskIdentifications?: RiskIdentificationRepository;
      signOffs?: SignOffRepository;
    } = {};

    obj.assessments = new AssessmentRepositoryAdapter(dynamoClient);
    obj.referenceComparisons = new ReferenceComparisonRepositoryAdapter(dynamoClient);
    obj.riskIdentifications = new RiskIdentificationRepositoryAdapter(dynamoClient);
    obj.signOffs = new SignOffRepositoryAdapter(dynamoClient);
    return {
      assessments: obj.assessments!,
      referenceComparisons: obj.referenceComparisons!,
      riskIdentifications: obj.riskIdentifications!,
      signOffs: obj.signOffs!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    assessments: {
      create: new ExecuteCreateRiskAssessment(executionContext, idGenerator, repos.assessments),
      list: new ExecuteListRiskAssessments(executionContext, idGenerator, repos.assessments),
    },
    referenceComparisons: {
      get: new ExecuteRecordReferenceComparison(executionContext, idGenerator, repos.referenceComparisons),
    },
    riskIdentifications: {
      get: new ExecuteRecordRiskIdentification(executionContext, idGenerator, repos.riskIdentifications),
    },
    signOffs: {
      get: new ExecuteSignOffRiskAssessment(executionContext, idGenerator, repos.signOffs),
    },
  };
  return { repos, useCases: useCases as AssessmentsDomainModule["useCases"] };
}
