/**
 * DataShiftRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataShiftRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DataShiftRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DataShiftRepository,
} from "@appetitebind/services/monitoring";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DataShiftRepositoryDdb } from "./data-shift-repository.ddb.js";

/**
 * DataShiftRepositoryAdapter
 *
 * Implements DataShiftRepository port for infrastructure layer.
 */
export class DataShiftRepositoryAdapter implements DataShiftRepository {
  private readonly ddb: DataShiftRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DataShiftRepositoryDdb(this.dynamoClient);
  }

  async ingestDataShiftSignal(input: Parameters<DataShiftRepository['ingestDataShiftSignal']>[0]): Promise<Awaited<ReturnType<DataShiftRepository['ingestDataShiftSignal']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.ingestDataShiftSignal(input);
  }
}
