/**
 * RiskIdentificationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RiskIdentificationRepository Port
 *
 * DDD: Application port for riskidentificationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RecordRiskIdentificationInput, RecordRiskIdentificationOutput } from "../dto/risk-identification.dto";
export interface RiskIdentificationRepository {
  recordRiskIdentification(input: RecordRiskIdentificationInput): Promise<RecordRiskIdentificationOutput>;
}

export type { RecordRiskIdentificationInput, RecordRiskIdentificationOutput } from "../dto/risk-identification.dto";
