/**
 * SignOffRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SignOffRepository Port
 *
 * DDD: Application port for signoffrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SignOffRiskAssessmentInput, SignOffRiskAssessmentOutput } from "../dto/sign-off.dto";
export interface SignOffRepository {
  signOffRiskAssessment(input: SignOffRiskAssessmentInput): Promise<SignOffRiskAssessmentOutput>;
}

export type { SignOffRiskAssessmentInput, SignOffRiskAssessmentOutput } from "../dto/sign-off.dto";
