/**
 * UseCase Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: usecases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/usecases.openapi.types.js";
import { schemas } from "../schemas/usecases.schemas.js";

/**
 * Entity: UseCaseEntity
 * Description: Represents the UseCase domain model.
 * Source: schemas.AiUseCase
 * Type: Persisted Entity (x-dynamodb)
 */
export const UseCaseEntitySchema = schemas.AiUseCase;
export type UseCaseEntity = components["schemas"]["AiUseCase"];
