/**
 * AppetiteCriterium DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appetite
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AppetiteCriterium DTOs
 *
 * DDD: Application DTOs for AppetiteCriterium use cases.
 */

import type { UpdateAppetiteCriteriaRequestInput } from "@appetitebind/core/appetite/types";

export type GetAppetiteCriteriaInput = {};

export type UpdateAppetiteCriteriaInput = UpdateAppetiteCriteriaRequestInput;

export type GetAppetiteCriteriaOutput = {};

export type UpdateAppetiteCriteriaOutput = {};
