/**
 * RiskIdentification Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { RiskIdentificationEntity } from "@appetitebind/core/assessments/models/index.js";
import { assessmentsSchemas } from "@appetitebind/core/assessments";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "asm";

export function createRiskIdentification(overrides: Partial<RiskIdentificationEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    identifiedAt: overrides.identifiedAt ?? new Date().toISOString(),
    riskIdentificationId: overrides.riskIdentificationId ?? `rid_${ulid().toLowerCase()}`,
    trigger: overrides.trigger ?? "use_expansion",
    useCaseId: overrides.useCaseId ?? `ucs_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return assessmentsSchemas.RiskIdentification.parse(raw);
}

export function riskIdentificationBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createRiskIdentification(overrides));
}
