/**
 * Repository interface for Issue
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  IssueEntity
} from "../models/issue.entity.js";
import type {
  ListIssuesParams,
  Issue
} from "../types/index.js";
/**
 * IssueRepository Interface
 */
export interface IssueRepository extends CreateReadRepository<IssueEntity, Issue, string, ListIssuesParams> {

}
