/**
 * Repository interface for SupervisoryExport
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SupervisoryExportEntity
} from "../models/supervisory-export.entity.js";
import type {
  SupervisoryExport
} from "../types/index.js";
/**
 * SupervisoryExportRepository Interface
 */
export interface SupervisoryExportRepository extends CreateReadRepository<SupervisoryExportEntity, SupervisoryExport, string, Record<string, never>> {

}
