/**
 * ListAppetiteBinding DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appetite
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListAppetiteBindingsParams } from "@appetitebind/core/appetite";

export function createListAppetiteBindingRequest(overrides: Partial<ListAppetiteBindingsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
