/**
 * GetKillSwitch handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getKillSwitch } from "@appetitebind/api-server/domains/controls/handlers";
import type { ControlsDDDDependencies } from "@appetitebind/api-server/domains/controls";
import { createKillSwitch as createKillSwitchEntity } from "@appetitebind/factories/controls";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@appetitebind/tests/shared";
import { CONTROLS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetKillSwitch", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ControlsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ControlsDDDDependencies>(
      CONTROLS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createKillSwitchEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetKillSwitch, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { useCaseId: entity.id };

    await getKillSwitch(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetKillSwitch.execute).toHaveBeenCalledWith(expect.objectContaining({ useCaseId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { useCaseId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetKillSwitch, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getKillSwitch(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
