/**
 * Controls Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const scheduleAiControlTest_Body = z
  .object({
    useCaseId: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
    testType: z.enum([
      'out_of_sample',
      'stress',
      'customer_journey',
      'data_bias',
      'accuracy',
    ]),
    frequency: z.string().optional(),
    ownerId: z.string().optional(),
  })
  .passthrough();
const submitControlTestEvidence_Body = z
  .object({
    outcome: z.enum(['passed', 'failed']),
    evidenceRef: z.string().optional(),
    detail: z.string().optional(),
    sampleSize: z.number().int().optional(),
  })
  .passthrough();
const setHandToHumanRules_Body = z
  .object({
    rules: z.array(
      z
        .object({
          condition: z.string(),
          destinationRole: z.string(),
          active: z.boolean().optional().default(true),
        })
        .passthrough()
    ),
  })
  .passthrough();
const registerKillSwitch_Body = z
  .object({
    useCaseId: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
    executableByRole: z.string(),
    bcpReference: z.string().optional(),
    remediationProtocol: z.string().optional(),
    drillCadenceDays: z.number().int(),
    lastDrillAt: z.string().datetime({ offset: true }).optional(),
    status: z
      .enum(['registered', 'drilled', 'executed', 'inactive'])
      .optional(),
    createdAt: z.string().datetime({ offset: true }),
    updatedAt: z.string().datetime({ offset: true }),
  })
  .passthrough();
const drillKillSwitch_Body = z
  .object({ executedBy: z.string(), notes: z.string().optional() })
  .passthrough();
const executeKillSwitch_Body = z
  .object({ executedBy: z.string(), rationale: z.string() })
  .passthrough();

export const schemas: any = {
  scheduleAiControlTest_Body,
  submitControlTestEvidence_Body,
  setHandToHumanRules_Body,
  registerKillSwitch_Body,
  drillKillSwitch_Body,
  executeKillSwitch_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/control-tests',
    alias: 'listAiControlTests',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'useCaseId',
        type: 'Query',
        schema: z
          .string()
          .regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/)
          .optional(),
      },
      {
        name: 'testType',
        type: 'Query',
        schema: z
          .enum([
            'out_of_sample',
            'stress',
            'customer_journey',
            'data_bias',
            'accuracy',
          ])
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  testId: z.string().regex(/^tst_[0-9A-HJKMNP-TV-Z]{26}$/),
                  useCaseId: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
                  testType: z.enum([
                    'out_of_sample',
                    'stress',
                    'customer_journey',
                    'data_bias',
                    'accuracy',
                  ]),
                  status: z.enum(['scheduled', 'running', 'passed', 'failed']),
                  frequency: z.string().optional(),
                  lastEvidenceAt: z
                    .string()
                    .datetime({ offset: true })
                    .optional(),
                  ownerId: z.string().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
  {
    method: 'post',
    path: '/v1/control-tests',
    alias: 'scheduleAiControlTest',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: scheduleAiControlTest_Body,
      },
    ],
    response: z
      .object({
        data: z
          .object({
            testId: z.string().regex(/^tst_[0-9A-HJKMNP-TV-Z]{26}$/),
            useCaseId: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
            testType: z.enum([
              'out_of_sample',
              'stress',
              'customer_journey',
              'data_bias',
              'accuracy',
            ]),
            status: z.enum(['scheduled', 'running', 'passed', 'failed']),
            frequency: z.string().optional(),
            lastEvidenceAt: z.string().datetime({ offset: true }).optional(),
            ownerId: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
  {
    method: 'post',
    path: '/v1/control-tests/:testId/evidence',
    alias: 'submitControlTestEvidence',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: submitControlTestEvidence_Body,
      },
      {
        name: 'testId',
        type: 'Path',
        schema: z.string().regex(/^tst_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            testId: z.string().regex(/^tst_[0-9A-HJKMNP-TV-Z]{26}$/),
            useCaseId: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
            testType: z.enum([
              'out_of_sample',
              'stress',
              'customer_journey',
              'data_bias',
              'accuracy',
            ]),
            status: z.enum(['scheduled', 'running', 'passed', 'failed']),
            frequency: z.string().optional(),
            lastEvidenceAt: z.string().datetime({ offset: true }).optional(),
            ownerId: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
  {
    method: 'get',
    path: '/v1/use-cases/:useCaseId/hand-to-human-rules',
    alias: 'listHandToHumanRules',
    requestFormat: 'json',
    parameters: [
      {
        name: 'useCaseId',
        type: 'Path',
        schema: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  handToHumanRuleId: z
                    .string()
                    .regex(/^h2h_[0-9A-HJKMNP-TV-Z]{26}$/),
                  useCaseId: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
                  condition: z.string(),
                  destinationRole: z.string(),
                  active: z.boolean().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
  {
    method: 'put',
    path: '/v1/use-cases/:useCaseId/hand-to-human-rules',
    alias: 'setHandToHumanRules',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: setHandToHumanRules_Body,
      },
      {
        name: 'useCaseId',
        type: 'Path',
        schema: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  handToHumanRuleId: z
                    .string()
                    .regex(/^h2h_[0-9A-HJKMNP-TV-Z]{26}$/),
                  useCaseId: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
                  condition: z.string(),
                  destinationRole: z.string(),
                  active: z.boolean().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
  {
    method: 'get',
    path: '/v1/use-cases/:useCaseId/kill-switch',
    alias: 'getKillSwitch',
    requestFormat: 'json',
    parameters: [
      {
        name: 'useCaseId',
        type: 'Path',
        schema: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            useCaseId: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
            executableByRole: z.string(),
            bcpReference: z.string().optional(),
            remediationProtocol: z.string().optional(),
            drillCadenceDays: z.number().int(),
            lastDrillAt: z.string().datetime({ offset: true }).optional(),
            status: z
              .enum(['registered', 'drilled', 'executed', 'inactive'])
              .optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'put',
    path: '/v1/use-cases/:useCaseId/kill-switch',
    alias: 'registerKillSwitch',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: registerKillSwitch_Body,
      },
      {
        name: 'useCaseId',
        type: 'Path',
        schema: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            useCaseId: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
            executableByRole: z.string(),
            bcpReference: z.string().optional(),
            remediationProtocol: z.string().optional(),
            drillCadenceDays: z.number().int(),
            lastDrillAt: z.string().datetime({ offset: true }).optional(),
            status: z
              .enum(['registered', 'drilled', 'executed', 'inactive'])
              .optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
  {
    method: 'post',
    path: '/v1/use-cases/:useCaseId/kill-switch/drill',
    alias: 'drillKillSwitch',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: drillKillSwitch_Body,
      },
      {
        name: 'useCaseId',
        type: 'Path',
        schema: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            killSwitchDrillId: z.string().regex(/^ksd_[0-9A-HJKMNP-TV-Z]{26}$/),
            useCaseId: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
            executedBy: z.string(),
            drilledAt: z.string().datetime({ offset: true }),
            timeToHaltSeconds: z.number().int().optional(),
            notes: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
  {
    method: 'post',
    path: '/v1/use-cases/:useCaseId/kill-switch/execute',
    alias: 'executeKillSwitch',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: executeKillSwitch_Body,
      },
      {
        name: 'useCaseId',
        type: 'Path',
        schema: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            useCaseId: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
            executableByRole: z.string(),
            bcpReference: z.string().optional(),
            remediationProtocol: z.string().optional(),
            drillCadenceDays: z.number().int(),
            lastDrillAt: z.string().datetime({ offset: true }).optional(),
            status: z
              .enum(['registered', 'drilled', 'executed', 'inactive'])
              .optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
