/**
 * Handlers for Assessment
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AssessmentsDomainModule } from "../dependencies/assessments-ddd.dependencies.js";
import type { CreateRiskAssessmentInput, ListRiskAssessmentsInput } from "@appetitebind/services/assessments";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/assessments
 * Operation: listRiskAssessments
 */
export async function listRiskAssessments(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], useCaseId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AssessmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    ...(request.query ?? {}),
  } as ListRiskAssessmentsInput;
  const result = await deps.useCases.assessments.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/assessments
 * Operation: createRiskAssessment
 */
export async function createRiskAssessment(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AssessmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    ...(request.body ?? {}),
  } as CreateRiskAssessmentInput;
  const result = await deps.useCases.assessments.create.execute(input);
  return reply.code(201).send(result);
}


