/**
 * Handlers for SignOff
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AssessmentsDomainModule } from "../dependencies/assessments-ddd.dependencies.js";
import type { SignOffRiskAssessmentInput } from "@appetitebind/services/assessments";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/assessments/{assessmentId}/sign-off
 * Operation: signOffRiskAssessment
 */
export async function signOffRiskAssessment(
  request: FastifyRequest<{ Params: { assessmentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AssessmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    assessmentId: request.params.assessmentId,
    ...(request.body ?? {}),
  } as SignOffRiskAssessmentInput;
  const result = await deps.useCases.signOffs.get.execute(input);
  return reply.code(200).send(result);
}


