/**
 * Controls DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Controls Domain Module - Composition root
 *
 * DDD: Composition root for controls domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ControlTestRepositoryAdapter,
  DrillRepositoryAdapter,
  EvidenceRepositoryAdapter,
  ExecuteRepositoryAdapter,
  HandToHumanRuleRepositoryAdapter,
  KillSwitchRepositoryAdapter,
} from "@appetitebind/adapters/controls";
import { getIdGeneratorService } from "@appetitebind/adapters";
import type { AdapterDynamoDBClient } from "@appetitebind/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteDrillKillSwitch,
  ExecuteExecuteKillSwitch,
  ExecuteGetKillSwitch,
  ExecuteListAiControlTests,
  ExecuteListHandToHumanRules,
  ExecuteRegisterKillSwitch,
  ExecuteScheduleAiControlTest,
  ExecuteSetHandToHumanRules,
  ExecuteSubmitControlTestEvidence,
} from "@appetitebind/services/controls/usecases";
// Ports (interfaces)
import type {
  ControlTestRepository,
  DrillRepository,
  EvidenceRepository,
  ExecuteRepository,
  HandToHumanRuleRepository,
  KillSwitchRepository,
} from "@appetitebind/services/controls/ports";

export interface ControlsDomainModule {
  repos: {
    controlTests: ControlTestRepository;
    drills: DrillRepository;
    evidences: EvidenceRepository;
    executes: ExecuteRepository;
    handToHumanRules: HandToHumanRuleRepository;
    killSwitches: KillSwitchRepository;
  };
  useCases: {
    controlTests: {
      get: ExecuteScheduleAiControlTest;
      list: ExecuteListAiControlTests;
    };
    drills: {
      get: ExecuteDrillKillSwitch;
    };
    evidences: {
      create: ExecuteSubmitControlTestEvidence;
    };
    executes: {
      create: ExecuteExecuteKillSwitch;
    };
    handToHumanRules: {
      list: ExecuteListHandToHumanRules;
      update: ExecuteSetHandToHumanRules;
    };
    killSwitches: {
      create: ExecuteRegisterKillSwitch;
      get: ExecuteGetKillSwitch;
    };
  };
}

export function buildControlsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ControlsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      controlTests?: ControlTestRepository;
      drills?: DrillRepository;
      evidences?: EvidenceRepository;
      executes?: ExecuteRepository;
      handToHumanRules?: HandToHumanRuleRepository;
      killSwitches?: KillSwitchRepository;
    } = {};

    obj.controlTests = new ControlTestRepositoryAdapter(dynamoClient);
    obj.drills = new DrillRepositoryAdapter(dynamoClient);
    obj.evidences = new EvidenceRepositoryAdapter(dynamoClient);
    obj.executes = new ExecuteRepositoryAdapter(dynamoClient);
    obj.handToHumanRules = new HandToHumanRuleRepositoryAdapter(dynamoClient);
    obj.killSwitches = new KillSwitchRepositoryAdapter(dynamoClient);
    return {
      controlTests: obj.controlTests!,
      drills: obj.drills!,
      evidences: obj.evidences!,
      executes: obj.executes!,
      handToHumanRules: obj.handToHumanRules!,
      killSwitches: obj.killSwitches!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    controlTests: {
      get: new ExecuteScheduleAiControlTest(executionContext, idGenerator, repos.controlTests),
      list: new ExecuteListAiControlTests(executionContext, idGenerator, repos.controlTests),
    },
    drills: {
      get: new ExecuteDrillKillSwitch(executionContext, idGenerator, repos.drills),
    },
    evidences: {
      create: new ExecuteSubmitControlTestEvidence(executionContext, idGenerator, repos.evidences),
    },
    executes: {
      create: new ExecuteExecuteKillSwitch(executionContext, idGenerator, repos.executes),
    },
    handToHumanRules: {
      list: new ExecuteListHandToHumanRules(executionContext, idGenerator, repos.handToHumanRules),
      update: new ExecuteSetHandToHumanRules(executionContext, idGenerator, repos.handToHumanRules),
    },
    killSwitches: {
      create: new ExecuteRegisterKillSwitch(executionContext, idGenerator, repos.killSwitches),
      get: new ExecuteGetKillSwitch(executionContext, idGenerator, repos.killSwitches),
    },
  };
  return { repos, useCases: useCases as ControlsDomainModule["useCases"] };
}
