/**
 * Routes for Drill
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { drillKillSwitch } from "../handlers/drill.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function drillRoutes(fastify: FastifyInstance) {
  // POST /v1/use-cases/{useCaseId}/kill-switch/drill (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/use-cases/:useCaseId/kill-switch/drill",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getControlsDependenciesForRequest();
        await drillKillSwitch(request, reply, deps);
      });
    }
  );


}
