/**
 * Routes for Evidence
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { submitControlTestEvidence } from "../handlers/evidence.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function evidenceRoutes(fastify: FastifyInstance) {
  // POST /v1/control-tests/{testId}/evidence (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/control-tests/:testId/evidence",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { testId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getControlsDependenciesForRequest();
        await submitControlTestEvidence(request, reply, deps);
      });
    }
  );


}
