/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { controlTestRoutes } from "./control-test.routes.js";
export { drillRoutes } from "./drill.routes.js";
export { evidenceRoutes } from "./evidence.routes.js";
export { executeRoutes } from "./execute.routes.js";
export { handToHumanRuleRoutes } from "./hand-to-human-rule.routes.js";
export { killSwitchRoutes } from "./kill-switch.routes.js";
