/**
 * Routes for KillSwitch
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getKillSwitch, registerKillSwitch } from "../handlers/kill-switch.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function killSwitchRoutes(fastify: FastifyInstance) {
  // GET /v1/use-cases/{useCaseId}/kill-switch (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/use-cases/:useCaseId/kill-switch",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getControlsDependenciesForRequest();
        await getKillSwitch(request, reply, deps);
      });
    }
  );


  // PUT /v1/use-cases/{useCaseId}/kill-switch (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/use-cases/:useCaseId/kill-switch",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getControlsDependenciesForRequest();
        await registerKillSwitch(request, reply, deps);
      });
    }
  );


}
