/**
 * DataShift Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { DataShiftEntity } from "@appetitebind/core/monitoring/models/index.js";
import { monitoringSchemas } from "@appetitebind/core/monitoring";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "mon";

export function createDataShift(overrides: Partial<DataShiftEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    dataShiftSignalId: overrides.dataShiftSignalId ?? `dst_${ulid().toLowerCase()}`,
    featureOrSegment: overrides.featureOrSegment ?? faker.lorem.word(),
    shiftMagnitude: overrides.shiftMagnitude ?? faker.number.int(),
    useCaseId: overrides.useCaseId ?? `ucs_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return monitoringSchemas.DataShiftSignal.parse(raw);
}

export function dataShiftBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createDataShift(overrides));
}
