/**
 * Complaint Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ComplaintEntity } from "@appetitebind/core/monitoring/models/index.js";
import { monitoringSchemas } from "@appetitebind/core/monitoring";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "mon";

export function createComplaint(overrides: Partial<ComplaintEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    complaintSignalId: overrides.complaintSignalId ?? `cmp_${ulid().toLowerCase()}`,
    taxonomy: overrides.taxonomy ?? "discrimination",
    useCaseId: overrides.useCaseId ?? `ucs_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return monitoringSchemas.ComplaintSignal.parse(raw);
}

export function complaintBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createComplaint(overrides));
}
