/**
 * Fairness DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Fairness Domain Module - Composition root
 *
 * DDD: Composition root for fairness domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  FairnessAssessmentRepositoryAdapter,
  FairnessPolicyRepositoryAdapter,
} from "@appetitebind/adapters/fairness";
import { getIdGeneratorService } from "@appetitebind/adapters";
import type { AdapterDynamoDBClient } from "@appetitebind/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateFairnessAssessment,
  ExecuteGetFairnessPolicy,
  ExecuteListFairnessAssessments,
  ExecuteUpdateFairnessPolicy,
} from "@appetitebind/services/fairness/usecases";
// Ports (interfaces)
import type {
  FairnessAssessmentRepository,
  FairnessPolicyRepository,
} from "@appetitebind/services/fairness/ports";

export interface FairnessDomainModule {
  repos: {
    assessments: FairnessAssessmentRepository;
    policies: FairnessPolicyRepository;
  };
  useCases: {
    assessments: {
      create: ExecuteCreateFairnessAssessment;
      list: ExecuteListFairnessAssessments;
    };
    policies: {
      get: ExecuteGetFairnessPolicy;
      update: ExecuteUpdateFairnessPolicy;
    };
  };
}

export function buildFairnessDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): FairnessDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      assessments?: FairnessAssessmentRepository;
      policies?: FairnessPolicyRepository;
    } = {};

    obj.assessments = new FairnessAssessmentRepositoryAdapter(dynamoClient);
    obj.policies = new FairnessPolicyRepositoryAdapter(dynamoClient);
    return {
      assessments: obj.assessments!,
      policies: obj.policies!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    assessments: {
      create: new ExecuteCreateFairnessAssessment(executionContext, idGenerator, repos.assessments),
      list: new ExecuteListFairnessAssessments(executionContext, idGenerator, repos.assessments),
    },
    policies: {
      get: new ExecuteGetFairnessPolicy(executionContext, idGenerator, repos.policies),
      update: new ExecuteUpdateFairnessPolicy(executionContext, idGenerator, repos.policies),
    },
  };
  return { repos, useCases: useCases as FairnessDomainModule["useCases"] };
}
