/**
 * BoardSnapshot Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/governance.openapi.types.js";
import { schemas } from "../schemas/governance.schemas.js";

/**
 * Entity: BoardSnapshotEntity
 * Description: Represents the BoardSnapshot domain model.
 * Source: schemas.BoardSnapshot
 * Type: Persisted Entity (x-dynamodb)
 */
export const BoardSnapshotEntitySchema = schemas.BoardSnapshot;
export type BoardSnapshotEntity = components["schemas"]["BoardSnapshot"];
