/**
 * Models barrel export - All Governance entities
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./board-snapshot.entity.js";
export * from "./issue.entity.js";
export * from "./supervisory-export.entity.js";
export * from "./variation.entity.js";
