/**
 * Repository interface for ReferenceComparison
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ReferenceComparisonEntity
} from "../models/reference-comparison.entity.js";
import type {
  RiskAssessment
} from "../types/index.js";
/**
 * ReferenceComparisonRepository Interface
 */
export interface ReferenceComparisonRepository extends CreateReadRepository<ReferenceComparisonEntity, RiskAssessment, string, Record<string, never>> {

}
