/**
 * Repository interface for RiskIdentification
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  RiskIdentificationEntity
} from "../models/risk-identification.entity.js";
import type {
  RiskIdentification
} from "../types/index.js";
/**
 * RiskIdentificationRepository Interface
 */
export interface RiskIdentificationRepository extends CreateReadRepository<RiskIdentificationEntity, RiskIdentification, string, Record<string, never>> {

}
