/**
 * Handlers for Execute
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ControlsDomainModule } from "../dependencies/controls-ddd.dependencies.js";
import type { ExecuteKillSwitchInput } from "@appetitebind/services/controls";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/use-cases/{useCaseId}/kill-switch/execute
 * Operation: executeKillSwitch
 */
export async function executeKillSwitch(
  request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ControlsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    useCaseId: request.params.useCaseId,
    ...(request.body ?? {}),
  } as ExecuteKillSwitchInput;
  const result = await deps.useCases.executes.create.execute(input);
  return reply.code(201).send(result);
}


