/**
 * Handlers for KillSwitch
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ControlsDomainModule } from "../dependencies/controls-ddd.dependencies.js";
import type { GetKillSwitchInput, RegisterKillSwitchInput } from "@appetitebind/services/controls";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/use-cases/{useCaseId}/kill-switch
 * Operation: getKillSwitch
 */
export async function getKillSwitch(
  request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ControlsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    useCaseId: request.params.useCaseId,
  } as GetKillSwitchInput;
  const result = await deps.useCases.killSwitches.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/use-cases/{useCaseId}/kill-switch
 * Operation: registerKillSwitch
 */
export async function registerKillSwitch(
  request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ControlsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    useCaseId: request.params.useCaseId,
    ...(request.body ?? {}),
  } as RegisterKillSwitchInput;
  const result = await deps.useCases.killSwitches.create.execute(input);
  return reply.code(200).send(result);
}


