/**
 * AppetiteCriteriumRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appetite
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AppetiteCriteriumRepository Port
 *
 * DDD: Application port for appetitecriteriumrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetAppetiteCriteriaInput, GetAppetiteCriteriaOutput, UpdateAppetiteCriteriaInput, UpdateAppetiteCriteriaOutput } from "../dto/appetite-criterium.dto";
export interface AppetiteCriteriumRepository {
  getAppetiteCriteria(input: GetAppetiteCriteriaInput): Promise<GetAppetiteCriteriaOutput>;
  updateAppetiteCriteria(input: UpdateAppetiteCriteriaInput): Promise<UpdateAppetiteCriteriaOutput>;
}

export type { GetAppetiteCriteriaInput, GetAppetiteCriteriaOutput, UpdateAppetiteCriteriaInput, UpdateAppetiteCriteriaOutput } from "../dto/appetite-criterium.dto";
