/**
 * Routes for DataShift
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { ingestDataShiftSignal } from "../handlers/data-shift.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function dataShiftRoutes(fastify: FastifyInstance) {
  // POST /v1/monitoring/data-shifts (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/monitoring/data-shifts",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMonitoringDependenciesForRequest();
        await ingestDataShiftSignal(request, reply, deps);
      });
    }
  );


}
