/**
 * BoardSnapshot DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BoardSnapshot DTOs
 *
 * DDD: Application DTOs for BoardSnapshot use cases.
 */

import type { PublishBoardSnapshotRequestInput } from "@appetitebind/core/governance/types";

export type PublishBoardSnapshotInput = PublishBoardSnapshotRequestInput;

export type PublishBoardSnapshotOutput = {};
