/**
 * FairnessPolicy Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { FairnessPolicyEntity } from "@appetitebind/core/fairness/models/index.js";
import { fairnessSchemas } from "@appetitebind/core/fairness";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "frn";

export function createFairnessPolicy(overrides: Partial<FairnessPolicyEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    fairnessPolicyId: overrides.fairnessPolicyId ?? `fpl_${ulid().toLowerCase()}`,
    thresholds: overrides.thresholds ?? [],
    version: overrides.version ?? faker.lorem.word(),
    ...overrides,
  };

  return fairnessSchemas.FairnessPolicy.parse(raw);
}

export function fairnessPolicyBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createFairnessPolicy(overrides));
}
