/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { assessmentRoutes } from "./assessment.routes.js";
export { referenceComparisonRoutes } from "./reference-comparison.routes.js";
export { riskIdentificationRoutes } from "./risk-identification.routes.js";
export { signOffRoutes } from "./sign-off.routes.js";
