/**
 * Routes for ReferenceComparison
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { recordReferenceComparison } from "../handlers/reference-comparison.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function referenceComparisonRoutes(fastify: FastifyInstance) {
  // POST /v1/assessments/{assessmentId}/reference-comparison (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/assessments/:assessmentId/reference-comparison",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { assessmentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAssessmentsDependenciesForRequest();
        await recordReferenceComparison(request, reply, deps);
      });
    }
  );


}
