/**
 * Governance DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Governance Domain Module - Composition root
 *
 * DDD: Composition root for governance domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  BoardSnapshotPublisherAdapter,
  IssueRepositoryAdapter,
  SupervisoryExportRepositoryAdapter,
  VariationRepositoryAdapter,
} from "@appetitebind/adapters/governance";
import { getIdGeneratorService } from "@appetitebind/adapters";
import type { AdapterDynamoDBClient } from "@appetitebind/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateSupervisoryExport,
  ExecuteListAlgorithmVariations,
  ExecuteListIssues,
  ExecuteOpenIssue,
  ExecutePublishBoardSnapshot,
  ExecuteRecordAlgorithmVariation,
} from "@appetitebind/services/governance/usecases";
// Ports (interfaces)
import type {
  BoardSnapshotPublisher,
  IssueRepository,
  SupervisoryExportRepository,
  VariationRepository,
} from "@appetitebind/services/governance/ports";

export interface GovernanceDomainModule {
  repos: {
    boardSnapshots: BoardSnapshotPublisher;
    issues: IssueRepository;
    supervisoryExports: SupervisoryExportRepository;
    variations: VariationRepository;
  };
  useCases: {
    boardSnapshots: {
      get: ExecutePublishBoardSnapshot;
    };
    issues: {
      get: ExecuteOpenIssue;
      list: ExecuteListIssues;
    };
    supervisoryExports: {
      create: ExecuteCreateSupervisoryExport;
    };
    variations: {
      get: ExecuteRecordAlgorithmVariation;
      list: ExecuteListAlgorithmVariations;
    };
  };
}

export function buildGovernanceDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): GovernanceDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      boardSnapshots?: BoardSnapshotPublisher;
      issues?: IssueRepository;
      supervisoryExports?: SupervisoryExportRepository;
      variations?: VariationRepository;
    } = {};

    const stubHttp = {
      get: async <T = unknown>() => ({ data: {} as T }),
      post: async <T = unknown>() => ({ data: {} as T }),
      put: async <T = unknown>() => ({ data: {} as T }),
      patch: async <T = unknown>() => ({ data: {} as T }),
      delete: async <T = unknown>() => ({ data: {} as T }),
    };
    obj.boardSnapshots = new BoardSnapshotPublisherAdapter(stubHttp);
    obj.issues = new IssueRepositoryAdapter(dynamoClient);
    obj.supervisoryExports = new SupervisoryExportRepositoryAdapter(dynamoClient);
    obj.variations = new VariationRepositoryAdapter(dynamoClient);
    return {
      boardSnapshots: obj.boardSnapshots!,
      issues: obj.issues!,
      supervisoryExports: obj.supervisoryExports!,
      variations: obj.variations!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    boardSnapshots: {
      get: new ExecutePublishBoardSnapshot(executionContext, idGenerator, repos.boardSnapshots),
    },
    issues: {
      get: new ExecuteOpenIssue(executionContext, idGenerator, repos.issues),
      list: new ExecuteListIssues(executionContext, idGenerator, repos.issues),
    },
    supervisoryExports: {
      create: new ExecuteCreateSupervisoryExport(executionContext, idGenerator, repos.supervisoryExports),
    },
    variations: {
      get: new ExecuteRecordAlgorithmVariation(executionContext, idGenerator, repos.variations),
      list: new ExecuteListAlgorithmVariations(executionContext, idGenerator, repos.variations),
    },
  };
  return { repos, useCases: useCases as GovernanceDomainModule["useCases"] };
}
