/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the governance domain.
 * Use these factories in tests to create test data.
 */

export { createBoardSnapshot } from "./board-snapshot/entity/board-snapshot.entity.factory.js";
export { createIssue } from "./issue/entity/issue.entity.factory.js";
export { createSupervisoryExport } from "./supervisory-export/entity/supervisory-export.entity.factory.js";
export { createVariation } from "./variation/entity/variation.entity.factory.js";
