/**
 * ReferenceComparison DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReferenceComparison DTOs
 *
 * DDD: Application DTOs for ReferenceComparison use cases.
 */

import type { RecordReferenceComparisonParams, RecordReferenceComparisonRequestInput } from "@appetitebind/core/assessments/types";

export type RecordReferenceComparisonInput = RecordReferenceComparisonParams & RecordReferenceComparisonRequestInput;

export type RecordReferenceComparisonOutput = {};
