/**
 * RiskIdentification DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RiskIdentification DTOs
 *
 * DDD: Application DTOs for RiskIdentification use cases.
 */

import type { RecordRiskIdentificationParams, RecordRiskIdentificationRequestInput } from "@appetitebind/core/assessments/types";

export type RecordRiskIdentificationInput = RecordRiskIdentificationParams & RecordRiskIdentificationRequestInput;

export type RecordRiskIdentificationOutput = {};
