/**
 * RecordReferenceComparison handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { recordReferenceComparison } from "@appetitebind/api-server/domains/assessments/handlers";
import type { AssessmentsDDDDependencies } from "@appetitebind/api-server/domains/assessments";
import { createReferenceComparison as createReferenceComparisonEntity } from "@appetitebind/factories/assessments";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@appetitebind/tests/shared";
import { ASSESSMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("RecordReferenceComparison", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AssessmentsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AssessmentsDDDDependencies>(
      ASSESSMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createReferenceComparisonEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRecordReferenceComparison, "execute").mockResolvedValue(useCaseResult);

    await recordReferenceComparison(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRecordReferenceComparison.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
