/**
 * BoardSnapshotPublisher Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BoardSnapshotPublisher Port
 *
 * DDD: Application port for boardsnapshotpublisher operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { PublishBoardSnapshotInput, PublishBoardSnapshotOutput } from "../dto/board-snapshot.dto";
export interface BoardSnapshotPublisher {
  publishBoardSnapshot(input: PublishBoardSnapshotInput): Promise<PublishBoardSnapshotOutput>;
}

export type { PublishBoardSnapshotInput, PublishBoardSnapshotOutput } from "../dto/board-snapshot.dto";
