/**
 * IssueRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IssueRepository Port
 *
 * DDD: Application port for issuerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListIssuesInput, ListIssuesOutput, OpenIssueInput, OpenIssueOutput } from "../dto/issue.dto";
export interface IssueRepository {
  listIssues(input: ListIssuesInput): Promise<ListIssuesOutput>;
  openIssue(input: OpenIssueInput): Promise<OpenIssueOutput>;
}

export type { ListIssuesInput, ListIssuesOutput, OpenIssueInput, OpenIssueOutput } from "../dto/issue.dto";
