/**
 * SupervisoryExportRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SupervisoryExportRepository Port
 *
 * DDD: Application port for supervisoryexportrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateSupervisoryExportInput, CreateSupervisoryExportOutput } from "../dto/supervisory-export.dto";
export interface SupervisoryExportRepository {
  createSupervisoryExport(input: CreateSupervisoryExportInput): Promise<CreateSupervisoryExportOutput>;
}

export type { CreateSupervisoryExportInput, CreateSupervisoryExportOutput } from "../dto/supervisory-export.dto";
