/**
 * SetHandToHumanRules handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { setHandToHumanRules } from "@appetitebind/api-server/domains/controls/handlers";
import type { ControlsDDDDependencies } from "@appetitebind/api-server/domains/controls";
import { createHandToHumanRule as createHandToHumanRuleEntity } from "@appetitebind/factories/controls";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@appetitebind/tests/shared";
import { CONTROLS_USE_CASES } from "../__factories__/use-cases.js";

describe("SetHandToHumanRules", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ControlsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ControlsDDDDependencies>(
      CONTROLS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createHandToHumanRuleEntity({ orgId });
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { useCaseId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeSetHandToHumanRules, "execute").mockResolvedValue(useCaseResult);

    await setHandToHumanRules(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeSetHandToHumanRules.execute).toHaveBeenCalledWith(expect.objectContaining({ useCaseId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
