/**
 * ExecuteRecordAlgorithmVariation - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRecordAlgorithmVariation Use Case
 *
 * DDD: Application use case for get Variation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RecordAlgorithmVariationInput, RecordAlgorithmVariationOutput } from "../dto/variation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@appetitebind/services/_shared/index.js";
import type { VariationRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRecordAlgorithmVariation {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly variation: VariationRepository
  ) {}

  async execute(input: RecordAlgorithmVariationInput): Promise<RecordAlgorithmVariationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec: changeSummary, reassessmentTriggered, versionFrom, versionTo
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).useCaseId) {
      throw new ValidationError("useCaseId is required");
    }
    const usecaseId = (input as any).useCaseId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.variation.recordAlgorithmVariation({ useCaseId: usecaseId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${usecaseId}`);
    }

    return entity as RecordAlgorithmVariationOutput;
  }
}
