/**
 * ExecuteListIssues - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListIssues Use Case
 *
 * DDD: Application use case for list Issue.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListIssuesInput, ListIssuesOutput } from "../dto/issue.dto";
import type { ExecutionContextService, IdGeneratorService } from "@appetitebind/services/_shared/index.js";
import type { IssueRepository } from "../ports";

export class ExecuteListIssues {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly issue: IssueRepository
  ) {}

  async execute(input: ListIssuesInput): Promise<ListIssuesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.issue.listIssues({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListIssuesOutput;
  }
}
