/**
 * ComplaintRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ComplaintRepository Port
 *
 * DDD: Application port for complaintrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { IngestComplaintSignalInput, IngestComplaintSignalOutput } from "../dto/complaint.dto";
export interface ComplaintRepository {
  ingestComplaintSignal(input: IngestComplaintSignalInput): Promise<IngestComplaintSignalOutput>;
}

export type { IngestComplaintSignalInput, IngestComplaintSignalOutput } from "../dto/complaint.dto";
