/**
 * HandToHumanRule Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { HandToHumanRuleEntity } from "@appetitebind/core/controls/models/index.js";
import { controlsSchemas } from "@appetitebind/core/controls";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ctl";

export function createHandToHumanRule(overrides: Partial<HandToHumanRuleEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    condition: overrides.condition ?? faker.lorem.word(),
    destinationRole: overrides.destinationRole ?? faker.lorem.word(),
    handToHumanRuleId: overrides.handToHumanRuleId ?? faker.string.uuid(),
    useCaseId: overrides.useCaseId ?? `ucs_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return controlsSchemas.HandToHumanRule.parse(raw);
}

export function handToHumanRuleBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createHandToHumanRule(overrides));
}
