/**
 * Repository interface for Drill
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  DrillEntity
} from "../models/drill.entity.js";
import type {
  KillSwitchDrill
} from "../types/index.js";
/**
 * DrillRepository Interface
 */
export interface DrillRepository extends CreateReadRepository<DrillEntity, KillSwitchDrill, string, Record<string, never>> {

}
