/**
 * Repository interface for Execute
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ExecuteEntity
} from "../models/execute.entity.js";
import type {
  KillSwitch
} from "../types/index.js";
/**
 * ExecuteRepository Interface
 */
export interface ExecuteRepository extends CreateReadRepository<ExecuteEntity, KillSwitch, string, Record<string, never>> {

}
