/**
 * Repository interface for HandToHumanRule
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  HandToHumanRuleEntity
} from "../models/hand-to-human-rule.entity.js";
import type {
  SetHandToHumanRulesRequestInput
} from "../types/index.js";
/**
 * HandToHumanRuleRepository Interface
 */
export interface HandToHumanRuleRepository extends UpdateReadRepository<HandToHumanRuleEntity, SetHandToHumanRulesRequestInput, string, Record<string, never>> {

}
