/**
 * Repository interface for KillSwitch
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  KillSwitchEntity
} from "../models/kill-switch.entity.js";
import type {
  KillSwitch
} from "../types/index.js";
/**
 * KillSwitchRepository Interface
 */
export interface KillSwitchRepository extends CreateReadRepository<KillSwitchEntity, KillSwitch, string, Record<string, never>> {

}
