/**
 * GetFairnessPolicy handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getFairnessPolicy } from "@appetitebind/api-server/domains/fairness/handlers";
import type { FairnessDDDDependencies } from "@appetitebind/api-server/domains/fairness";
import { createFairnessPolicy as createFairnessPolicyEntity } from "@appetitebind/factories/fairness";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@appetitebind/tests/shared";
import { FAIRNESS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetFairnessPolicy", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: FairnessDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<FairnessDDDDependencies>(
      FAIRNESS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity", async () => {
    const entity = createFairnessPolicyEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetFairnessPolicy, "execute").mockResolvedValue(useCaseResult);

    await getFairnessPolicy(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetFairnessPolicy.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
