/**
 * ControlTestRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ControlTestRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ControlTestRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ControlTestRepository,
} from "@appetitebind/services/controls";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ControlTestRepositoryDdb } from "./control-test-repository.ddb.js";

/**
 * ControlTestRepositoryAdapter
 *
 * Implements ControlTestRepository port for infrastructure layer.
 */
export class ControlTestRepositoryAdapter implements ControlTestRepository {
  private readonly ddb: ControlTestRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ControlTestRepositoryDdb(this.dynamoClient);
  }

  async listAiControlTests(input: Parameters<ControlTestRepository['listAiControlTests']>[0]): Promise<Awaited<ReturnType<ControlTestRepository['listAiControlTests']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAiControlTests(input);
  }

  async scheduleAiControlTest(input: Parameters<ControlTestRepository['scheduleAiControlTest']>[0]): Promise<Awaited<ReturnType<ControlTestRepository['scheduleAiControlTest']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.scheduleAiControlTest(input);
  }
}
