/**
 * DrillRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DrillRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DrillRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DrillRepository,
} from "@appetitebind/services/controls";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DrillRepositoryDdb } from "./drill-repository.ddb.js";

/**
 * DrillRepositoryAdapter
 *
 * Implements DrillRepository port for infrastructure layer.
 */
export class DrillRepositoryAdapter implements DrillRepository {
  private readonly ddb: DrillRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DrillRepositoryDdb(this.dynamoClient);
  }

  async drillKillSwitch(input: Parameters<DrillRepository['drillKillSwitch']>[0]): Promise<Awaited<ReturnType<DrillRepository['drillKillSwitch']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.drillKillSwitch(input);
  }
}
