/**
 * HandToHumanRuleRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HandToHumanRuleRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements HandToHumanRuleRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  HandToHumanRuleRepository,
} from "@appetitebind/services/controls";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { HandToHumanRuleRepositoryDdb } from "./hand-to-human-rule-repository.ddb.js";

/**
 * HandToHumanRuleRepositoryAdapter
 *
 * Implements HandToHumanRuleRepository port for infrastructure layer.
 */
export class HandToHumanRuleRepositoryAdapter implements HandToHumanRuleRepository {
  private readonly ddb: HandToHumanRuleRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new HandToHumanRuleRepositoryDdb(this.dynamoClient);
  }

  async listHandToHumanRules(input: Parameters<HandToHumanRuleRepository['listHandToHumanRules']>[0]): Promise<Awaited<ReturnType<HandToHumanRuleRepository['listHandToHumanRules']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listHandToHumanRules(input);
  }

  async setHandToHumanRules(input: Parameters<HandToHumanRuleRepository['setHandToHumanRules']>[0]): Promise<Awaited<ReturnType<HandToHumanRuleRepository['setHandToHumanRules']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.setHandToHumanRules(input);
  }
}
