/**
 * KillSwitchRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * KillSwitchRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements KillSwitchRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  KillSwitchRepository,
} from "@appetitebind/services/controls";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { KillSwitchRepositoryDdb } from "./kill-switch-repository.ddb.js";

/**
 * KillSwitchRepositoryAdapter
 *
 * Implements KillSwitchRepository port for infrastructure layer.
 */
export class KillSwitchRepositoryAdapter implements KillSwitchRepository {
  private readonly ddb: KillSwitchRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new KillSwitchRepositoryDdb(this.dynamoClient);
  }

  async getKillSwitch(input: Parameters<KillSwitchRepository['getKillSwitch']>[0]): Promise<Awaited<ReturnType<KillSwitchRepository['getKillSwitch']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getKillSwitch(input);
  }

  async registerKillSwitch(input: Parameters<KillSwitchRepository['registerKillSwitch']>[0]): Promise<Awaited<ReturnType<KillSwitchRepository['registerKillSwitch']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerKillSwitch(input);
  }
}
