/**
 * ExecuteListHandToHumanRules - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListHandToHumanRules Use Case
 *
 * DDD: Application use case for list HandToHumanRule.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListHandToHumanRulesInput, ListHandToHumanRulesOutput } from "../dto/hand-to-human-rule.dto";
import type { ExecutionContextService, IdGeneratorService } from "@appetitebind/services/_shared/index.js";
import type { HandToHumanRuleRepository } from "../ports";

export class ExecuteListHandToHumanRules {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly handToHumanRule: HandToHumanRuleRepository
  ) {}

  async execute(input: ListHandToHumanRulesInput): Promise<ListHandToHumanRulesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ctlId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.handToHumanRule.listHandToHumanRules({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListHandToHumanRulesOutput;
  }
}
