/**
 * ExecuteScheduleAiControlTest - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteScheduleAiControlTest Use Case
 *
 * DDD: Application use case for get ControlTest.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ScheduleAiControlTestInput, ScheduleAiControlTestOutput } from "../dto/control-test.dto";
import type { ExecutionContextService, IdGeneratorService } from "@appetitebind/services/_shared/index.js";
import type { ControlTestRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteScheduleAiControlTest {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly controlTest: ControlTestRepository
  ) {}

  async execute(input: ScheduleAiControlTestInput): Promise<ScheduleAiControlTestOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ctlId();

    // All field names extracted from OpenAPI spec: frequency, ownerId, testType, useCaseId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).ownerId) {
      throw new ValidationError("ownerId is required");
    }
    const ownerId = (input as any).ownerId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.controlTest.scheduleAiControlTest({ ownerId: ownerId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${ownerId}`);
    }

    return entity as ScheduleAiControlTestOutput;
  }
}
