/**
 * ExecuteListAiControlTests - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAiControlTests Use Case
 *
 * DDD: Application use case for list ControlTest.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAiControlTestsInput, ListAiControlTestsOutput } from "../dto/control-test.dto";
import type { ExecutionContextService, IdGeneratorService } from "@appetitebind/services/_shared/index.js";
import type { ControlTestRepository } from "../ports";

export class ExecuteListAiControlTests {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly controlTest: ControlTestRepository
  ) {}

  async execute(input: ListAiControlTestsInput): Promise<ListAiControlTestsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ctlId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.controlTest.listAiControlTests({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAiControlTestsOutput;
  }
}
