/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the fairness domain.
 * Use these factories in tests to create test data.
 */

export { createFairnessAssessment } from "./fairness-assessment/entity/fairness-assessment.entity.factory.js";
export { createFairnessPolicy } from "./fairness-policy/entity/fairness-policy.entity.factory.js";
