/**
 * ExecuteIngestMonitoringMetric - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteIngestMonitoringMetric Use Case
 *
 * DDD: Application use case for get Metric.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { IngestMonitoringMetricInput, IngestMonitoringMetricOutput } from "../dto/metric.dto";
import type { ExecutionContextService, IdGeneratorService } from "@appetitebind/services/_shared/index.js";
import type { MetricRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteIngestMonitoringMetric {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly metric: MetricRepository
  ) {}

  async execute(input: IngestMonitoringMetricInput): Promise<IngestMonitoringMetricOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.monId();

    // All field names extracted from OpenAPI spec: category, name, observedAt, threshold, useCaseId, value
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).useCaseId) {
      throw new ValidationError("useCaseId is required");
    }
    const usecaseId = (input as any).useCaseId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.metric.ingestMonitoringMetric({ useCaseId: usecaseId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${usecaseId}`);
    }

    return entity as IngestMonitoringMetricOutput;
  }
}
