/**
 * ExecuteIngestDataShiftSignal - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteIngestDataShiftSignal Use Case
 *
 * DDD: Application use case for get DataShift.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { IngestDataShiftSignalInput, IngestDataShiftSignalOutput } from "../dto/data-shift.dto";
import type { ExecutionContextService, IdGeneratorService } from "@appetitebind/services/_shared/index.js";
import type { DataShiftRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteIngestDataShiftSignal {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dataShift: DataShiftRepository
  ) {}

  async execute(input: IngestDataShiftSignalInput): Promise<IngestDataShiftSignalOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.monId();

    // All field names extracted from OpenAPI spec: createdAt, dataShiftSignalId, detectedAt, featureOrSegment, shiftMagnitude, updatedAt, useCaseId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).dataShiftSignalId) {
      throw new ValidationError("dataShiftSignalId is required");
    }
    const datashiftsignalId = (input as any).dataShiftSignalId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.dataShift.ingestDataShiftSignal({ dataShiftSignalId: datashiftsignalId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${datashiftsignalId}`);
    }

    return entity as IngestDataShiftSignalOutput;
  }
}
