/**
 * ExecuteIngestComplaintSignal - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteIngestComplaintSignal Use Case
 *
 * DDD: Application use case for get Complaint.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { IngestComplaintSignalInput, IngestComplaintSignalOutput } from "../dto/complaint.dto";
import type { ExecutionContextService, IdGeneratorService } from "@appetitebind/services/_shared/index.js";
import type { ComplaintRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteIngestComplaintSignal {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly complaint: ComplaintRepository
  ) {}

  async execute(input: IngestComplaintSignalInput): Promise<IngestComplaintSignalOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.monId();

    // All field names extracted from OpenAPI spec: complaintSignalId, createdAt, externalComplaintId, receivedAt, taxonomy, updatedAt, useCaseId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).complaintSignalId) {
      throw new ValidationError("complaintSignalId is required");
    }
    const complaintsignalId = (input as any).complaintSignalId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.complaint.ingestComplaintSignal({ complaintSignalId: complaintsignalId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${complaintsignalId}`);
    }

    return entity as IngestComplaintSignalOutput;
  }
}
