/**
 * Handlers for DataShift
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { MonitoringDomainModule } from "../dependencies/monitoring-ddd.dependencies.js";
import type { IngestDataShiftSignalInput } from "@appetitebind/services/monitoring";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/monitoring/data-shifts
 * Operation: ingestDataShiftSignal
 */
export async function ingestDataShiftSignal(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: MonitoringDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    ...(request.body ?? {}),
  } as IngestDataShiftSignalInput;
  const result = await deps.useCases.dataShifts.get.execute(input);
  return reply.code(200).send(result);
}


