/**
 * RiskIdentificationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RiskIdentificationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RiskIdentificationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RiskIdentificationRepository,
} from "@appetitebind/services/assessments";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RiskIdentificationRepositoryDdb } from "./risk-identification-repository.ddb.js";

/**
 * RiskIdentificationRepositoryAdapter
 *
 * Implements RiskIdentificationRepository port for infrastructure layer.
 */
export class RiskIdentificationRepositoryAdapter implements RiskIdentificationRepository {
  private readonly ddb: RiskIdentificationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RiskIdentificationRepositoryDdb(this.dynamoClient);
  }

  async recordRiskIdentification(input: Parameters<RiskIdentificationRepository['recordRiskIdentification']>[0]): Promise<Awaited<ReturnType<RiskIdentificationRepository['recordRiskIdentification']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.recordRiskIdentification(input);
  }
}
