/**
 * SignOffRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SignOffRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SignOffRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SignOffRepository,
} from "@appetitebind/services/assessments";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SignOffRepositoryDdb } from "./sign-off-repository.ddb.js";

/**
 * SignOffRepositoryAdapter
 *
 * Implements SignOffRepository port for infrastructure layer.
 */
export class SignOffRepositoryAdapter implements SignOffRepository {
  private readonly ddb: SignOffRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SignOffRepositoryDdb(this.dynamoClient);
  }

  async signOffRiskAssessment(input: Parameters<SignOffRepository['signOffRiskAssessment']>[0]): Promise<Awaited<ReturnType<SignOffRepository['signOffRiskAssessment']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.signOffRiskAssessment(input);
  }
}
