/**
 * Repository interface for FairnessPolicy
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  FairnessPolicyEntity
} from "../models/fairness-policy.entity.js";
import type {
  UpdateFairnessPolicyRequestInput
} from "../types/index.js";
/**
 * FairnessPolicyRepository Interface
 */
export interface FairnessPolicyRepository extends UpdateReadRepository<FairnessPolicyEntity, UpdateFairnessPolicyRequestInput, string, Record<string, never>> {

}
