/**
 * Repository Generator exports
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./fairness-policy.repository.js";
export * from "./fairness-assessment.repository.js";
