/**
 * FairnessPolicy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FairnessPolicy DTOs
 *
 * DDD: Application DTOs for FairnessPolicy use cases.
 */

import type { UpdateFairnessPolicyRequestInput } from "@appetitebind/core/fairness/types";

export type GetFairnessPolicyInput = {};

export type UpdateFairnessPolicyInput = UpdateFairnessPolicyRequestInput;

export type GetFairnessPolicyOutput = {};

export type UpdateFairnessPolicyOutput = {};
