/**
 * FairnessAssessment DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FairnessAssessment DTOs
 *
 * DDD: Application DTOs for FairnessAssessment use cases.
 */

import type { CreateFairnessAssessmentParams, CreateFairnessAssessmentRequestInput, ListFairnessAssessmentsParams } from "@appetitebind/core/fairness/types";

export type ListFairnessAssessmentsInput = ListFairnessAssessmentsParams;

export type CreateFairnessAssessmentInput = CreateFairnessAssessmentParams & CreateFairnessAssessmentRequestInput;

export type ListFairnessAssessmentsOutput = {};

export type CreateFairnessAssessmentOutput = {};
