/**
 * Routes for FairnessPolicy
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getFairnessPolicy, updateFairnessPolicy } from "../handlers/fairness-policy.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function fairnessPolicyRoutes(fastify: FastifyInstance) {
  // GET /v1/fairness-policy (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/fairness-policy",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFairnessDependenciesForRequest();
        await getFairnessPolicy(request, reply, deps);
      });
    }
  );


  // PUT /v1/fairness-policy (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/fairness-policy",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFairnessDependenciesForRequest();
        await updateFairnessPolicy(request, reply, deps);
      });
    }
  );


}
