/**
 * Routes for FairnessAssessment
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createFairnessAssessment, listFairnessAssessments } from "../handlers/fairness-assessment.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function fairnessAssessmentRoutes(fastify: FastifyInstance) {
  // POST /v1/use-cases/{useCaseId}/fairness-assessments (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/use-cases/:useCaseId/fairness-assessments",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFairnessDependenciesForRequest();
        await createFairnessAssessment(request, reply, deps);
      });
    }
  );


  // GET /v1/use-cases/{useCaseId}/fairness-assessments (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/use-cases/:useCaseId/fairness-assessments",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFairnessDependenciesForRequest();
        await listFairnessAssessments(request, reply, deps);
      });
    }
  );


}
