/**
 * ListRiskAssessments handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listRiskAssessments } from "@appetitebind/api-server/domains/assessments/handlers";
import type { AssessmentsDDDDependencies } from "@appetitebind/api-server/domains/assessments";
import { createAssessment as createAssessmentEntity } from "@appetitebind/factories/assessments";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@appetitebind/tests/shared";
import { ASSESSMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListRiskAssessments", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AssessmentsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AssessmentsDDDDependencies>(
      ASSESSMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createAssessmentEntity({ orgId }),
      createAssessmentEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListRiskAssessments, "execute").mockResolvedValue(useCaseResult);

    await listRiskAssessments(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListRiskAssessments.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
