/**
 * Handlers for Owner
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: usecases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { UsecasesDomainModule } from "../dependencies/usecases-ddd.dependencies.js";
import type { AssignUseCaseOwnerInput } from "@appetitebind/services/usecases";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for PUT /v1/use-cases/{useCaseId}/owner
 * Operation: assignUseCaseOwner
 */
export async function assignUseCaseOwner(
  request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: UsecasesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    useCaseId: request.params.useCaseId,
    ...(request.body ?? {}),
  } as AssignUseCaseOwnerInput;
  const result = await deps.useCases.owners.get.execute(input);
  return reply.code(200).send(result);
}


