/**
 * SupervisoryExport Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { SupervisoryExportEntity } from "@appetitebind/core/governance/models/index.js";
import { governanceSchemas } from "@appetitebind/core/governance";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "gov";

export function createSupervisoryExport(overrides: Partial<SupervisoryExportEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    supervisoryExportId: overrides.supervisoryExportId ?? `sup_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return governanceSchemas.SupervisoryExport.parse(raw);
}

export function supervisoryExportBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createSupervisoryExport(overrides));
}
