/**
 * ExecuteBindUseCaseToAppetite - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appetite
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteBindUseCaseToAppetite Use Case
 *
 * DDD: Application use case for get AppetiteBinding.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { BindUseCaseToAppetiteInput, BindUseCaseToAppetiteOutput } from "../dto/appetite-binding.dto";
import type { ExecutionContextService, IdGeneratorService } from "@appetitebind/services/_shared/index.js";
import type { AppetiteBindingRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteBindUseCaseToAppetite {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly appetiteBinding: AppetiteBindingRepository
  ) {}

  async execute(input: BindUseCaseToAppetiteInput): Promise<BindUseCaseToAppetiteOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.aptId();

    // All field names extracted from OpenAPI spec: answers, conditions, decision, expiresAt, residualRiskLevel
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).useCaseId) {
      throw new ValidationError("useCaseId is required");
    }
    const usecaseId = (input as any).useCaseId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.appetiteBinding.bindUseCaseToAppetite({ useCaseId: usecaseId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${usecaseId}`);
    }

    return entity as BindUseCaseToAppetiteOutput;
  }
}
