/**
 * ExecuteUpdateAppetiteCriteria - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appetite
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateAppetiteCriteria Use Case
 *
 * DDD: Application use case for update AppetiteCriterium.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateAppetiteCriteriaInput, UpdateAppetiteCriteriaOutput } from "../dto/appetite-criterium.dto";
import type { ExecutionContextService, IdGeneratorService } from "@appetitebind/services/_shared/index.js";
import type { AppetiteCriteriumRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateAppetiteCriteria {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly appetiteCriterium: AppetiteCriteriumRepository
  ) {}

  async execute(input: UpdateAppetiteCriteriaInput): Promise<UpdateAppetiteCriteriaOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.aptId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).criteriaId) {
      throw new ValidationError("criteriaId is required");
    }
    const criteriaId = (input as any).criteriaId;
    // No get/list operation for this resource - call update directly
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.appetiteCriterium.updateAppetiteCriteria({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateAppetiteCriteriaOutput;
  }
}
