/**
 * Handlers for FairnessPolicy
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { FairnessDomainModule } from "../dependencies/fairness-ddd.dependencies.js";
import type { GetFairnessPolicyInput, UpdateFairnessPolicyInput } from "@appetitebind/services/fairness";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/fairness-policy
 * Operation: getFairnessPolicy
 */
export async function getFairnessPolicy(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: FairnessDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {};
  const result = await deps.useCases.policies.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/fairness-policy
 * Operation: updateFairnessPolicy
 */
export async function updateFairnessPolicy(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: FairnessDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    ...(request.body ?? {}),
  } as UpdateFairnessPolicyInput;
  const result = await deps.useCases.policies.update.execute(input);
  return reply.code(200).send(result);
}


