/**
 * ExecuteRecordReferenceComparison - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRecordReferenceComparison Use Case
 *
 * DDD: Application use case for get ReferenceComparison.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RecordReferenceComparisonInput, RecordReferenceComparisonOutput } from "../dto/reference-comparison.dto";
import type { ExecutionContextService, IdGeneratorService } from "@appetitebind/services/_shared/index.js";
import type { ReferenceComparisonRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRecordReferenceComparison {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly referenceComparison: ReferenceComparisonRepository
  ) {}

  async execute(input: RecordReferenceComparisonInput): Promise<RecordReferenceComparisonOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.asmId();

    // All field names extracted from OpenAPI spec: decisionDriversReviewed, materialVariance, rationale, referenceType, varianceSummary
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).assessmentId) {
      throw new ValidationError("assessmentId is required");
    }
    const assessmentId = (input as any).assessmentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.referenceComparison.recordReferenceComparison({ assessmentId: assessmentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${assessmentId}`);
    }

    return entity as RecordReferenceComparisonOutput;
  }
}
