/**
 * ExecuteSignOffRiskAssessment - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSignOffRiskAssessment Use Case
 *
 * DDD: Application use case for get SignOff.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SignOffRiskAssessmentInput, SignOffRiskAssessmentOutput } from "../dto/sign-off.dto";
import type { ExecutionContextService, IdGeneratorService } from "@appetitebind/services/_shared/index.js";
import type { SignOffRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteSignOffRiskAssessment {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly signOff: SignOffRepository
  ) {}

  async execute(input: SignOffRiskAssessmentInput): Promise<SignOffRiskAssessmentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.asmId();

    // All field names extracted from OpenAPI spec: comments, decision, line, roleId, signedAt
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).assessmentId) {
      throw new ValidationError("assessmentId is required");
    }
    const assessmentId = (input as any).assessmentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.signOff.signOffRiskAssessment({ assessmentId: assessmentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${assessmentId}`);
    }

    return entity as SignOffRiskAssessmentOutput;
  }
}
