/**
 * Repository interface for Complaint
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ComplaintEntity
} from "../models/complaint.entity.js";
import type {
  ComplaintSignal
} from "../types/index.js";
/**
 * ComplaintRepository Interface
 */
export interface ComplaintRepository extends CreateReadRepository<ComplaintEntity, ComplaintSignal, string, Record<string, never>> {

}
