/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@appetitebind/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@appetitebind/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@appetitebind/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _appetite from "./appetite/index.js";
import * as _assessments from "./assessments/index.js";
import * as _controls from "./controls/index.js";
import * as _fairness from "./fairness/index.js";
import * as _governance from "./governance/index.js";
import * as _identity from "./identity/index.js";
import * as _monitoring from "./monitoring/index.js";
import * as _predictions from "./predictions/index.js";
import * as _usecases from "./usecases/index.js";

// Export as namespaces
export const appetite = _appetite;
export const assessments = _assessments;
export const controls = _controls;
export const fairness = _fairness;
export const governance = _governance;
export const identity = _identity;
export const monitoring = _monitoring;
export const predictions = _predictions;
export const usecases = _usecases;
