/**
 * Issue Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { IssueEntity } from "@appetitebind/core/governance/models/index.js";
import { governanceSchemas } from "@appetitebind/core/governance";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "gov";

export function createIssue(overrides: Partial<IssueEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    issueId: overrides.issueId ?? `iss_${ulid().toLowerCase()}`,
    status: overrides.status ?? "open",
    title: overrides.title ?? faker.lorem.sentence(),
    useCaseId: overrides.useCaseId ?? `ucs_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return governanceSchemas.Issue.parse(raw);
}

export function issueBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createIssue(overrides));
}
