/**
 * ReferenceComparison Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/assessments.openapi.types.js";
import { schemas } from "../schemas/assessments.schemas.js";

/**
 * Entity: ReferenceComparisonEntity
 * Description: Represents the ReferenceComparison domain model.
 * Source: schemas.RiskAssessment
 * Type: Persisted Entity (x-dynamodb)
 */
export const ReferenceComparisonEntitySchema = schemas.RiskAssessment;
export type ReferenceComparisonEntity = components["schemas"]["RiskAssessment"];
