/**
 * RiskIdentification Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/assessments.openapi.types.js";
import { schemas } from "../schemas/assessments.schemas.js";

/**
 * Entity: RiskIdentificationEntity
 * Description: Represents the RiskIdentification domain model.
 * Source: schemas.RiskIdentification
 * Type: Persisted Entity (x-dynamodb)
 */
export const RiskIdentificationEntitySchema = schemas.RiskIdentification;
export type RiskIdentificationEntity = components["schemas"]["RiskIdentification"];
