/**
 * Handlers index
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./board-snapshot.handlers.js";
export * from "./issue.handlers.js";
export * from "./supervisory-export.handlers.js";
export * from "./variation.handlers.js";
