/**
 * Handlers for Issue
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GovernanceDomainModule } from "../dependencies/governance-ddd.dependencies.js";
import type { ListIssuesInput, OpenIssueInput } from "@appetitebind/services/governance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/issues
 * Operation: listIssues
 */
export async function listIssues(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], useCaseId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    ...(request.query ?? {}),
  } as ListIssuesInput;
  const result = await deps.useCases.issues.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/issues
 * Operation: openIssue
 */
export async function openIssue(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    ...(request.body ?? {}),
  } as OpenIssueInput;
  const result = await deps.useCases.issues.get.execute(input);
  return reply.code(201).send(result);
}


