/**
 * GetAppetiteCriteria handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appetite
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getAppetiteCriteria } from "@appetitebind/api-server/domains/appetite/handlers";
import type { AppetiteDDDDependencies } from "@appetitebind/api-server/domains/appetite";
import { createAppetiteCriterium as createAppetiteCriteriumEntity } from "@appetitebind/factories/appetite";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@appetitebind/tests/shared";
import { APPETITE_USE_CASES } from "../__factories__/use-cases.js";

describe("GetAppetiteCriteria", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AppetiteDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AppetiteDDDDependencies>(
      APPETITE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity", async () => {
    const entity = createAppetiteCriteriumEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetAppetiteCriteria, "execute").mockResolvedValue(useCaseResult);

    await getAppetiteCriteria(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetAppetiteCriteria.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
