/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { boardSnapshotRoutes } from "./board-snapshot.routes.js";
export { issueRoutes } from "./issue.routes.js";
export { supervisoryExportRoutes } from "./supervisory-export.routes.js";
export { variationRoutes } from "./variation.routes.js";
