/**
 * Routes for Variation
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listAlgorithmVariations, recordAlgorithmVariation } from "../handlers/variation.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function variationRoutes(fastify: FastifyInstance) {
  // GET /v1/use-cases/{useCaseId}/variations (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/use-cases/:useCaseId/variations",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGovernanceDependenciesForRequest();
        await listAlgorithmVariations(request, reply, deps);
      });
    }
  );


  // POST /v1/use-cases/{useCaseId}/variations (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/use-cases/:useCaseId/variations",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGovernanceDependenciesForRequest();
        await recordAlgorithmVariation(request, reply, deps);
      });
    }
  );


}
