/**
 * Handlers for AppetiteBinding
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appetite
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AppetiteDomainModule } from "../dependencies/appetite-ddd.dependencies.js";
import type { BindUseCaseToAppetiteInput, ListAppetiteBindingsInput } from "@appetitebind/services/appetite";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/use-cases/{useCaseId}/appetite-bindings
 * Operation: listAppetiteBindings
 */
export async function listAppetiteBindings(
  request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AppetiteDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    useCaseId: request.params.useCaseId,
  } as ListAppetiteBindingsInput;
  const result = await deps.useCases.bindings.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/use-cases/{useCaseId}/appetite-bindings
 * Operation: bindUseCaseToAppetite
 */
export async function bindUseCaseToAppetite(
  request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AppetiteDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    useCaseId: request.params.useCaseId,
    ...(request.body ?? {}),
  } as BindUseCaseToAppetiteInput;
  const result = await deps.useCases.bindings.get.execute(input);
  return reply.code(201).send(result);
}


