/**
 * Handlers for AppetiteCriterium
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appetite
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AppetiteDomainModule } from "../dependencies/appetite-ddd.dependencies.js";
import type { GetAppetiteCriteriaInput, UpdateAppetiteCriteriaInput } from "@appetitebind/services/appetite";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/appetite-criteria
 * Operation: getAppetiteCriteria
 */
export async function getAppetiteCriteria(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AppetiteDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {};
  const result = await deps.useCases.criteria.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/appetite-criteria
 * Operation: updateAppetiteCriteria
 */
export async function updateAppetiteCriteria(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AppetiteDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    ...(request.body ?? {}),
  } as UpdateAppetiteCriteriaInput;
  const result = await deps.useCases.criteria.update.execute(input);
  return reply.code(200).send(result);
}


