/**
 * ExecuteUpdateFairnessPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateFairnessPolicy Use Case
 *
 * DDD: Application use case for update FairnessPolicy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateFairnessPolicyInput, UpdateFairnessPolicyOutput } from "../dto/fairness-policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@appetitebind/services/_shared/index.js";
import type { FairnessPolicyRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateFairnessPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly fairnessPolicy: FairnessPolicyRepository
  ) {}

  async execute(input: UpdateFairnessPolicyInput): Promise<UpdateFairnessPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.frnId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).fairnessPolicyId) {
      throw new ValidationError("fairnessPolicyId is required");
    }
    const fairnesspolicyId = (input as any).fairnessPolicyId;

    // Load existing entity
    const existing = await this.fairnessPolicy.getFairnessPolicy({ fairnessPolicyId: fairnesspolicyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${fairnesspolicyId}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.fairnessPolicy.updateFairnessPolicy({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateFairnessPolicyOutput;
  }
}
