/**
 * ExecuteListFairnessAssessments - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListFairnessAssessments Use Case
 *
 * DDD: Application use case for list FairnessAssessment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListFairnessAssessmentsInput, ListFairnessAssessmentsOutput } from "../dto/fairness-assessment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@appetitebind/services/_shared/index.js";
import type { FairnessAssessmentRepository } from "../ports";

export class ExecuteListFairnessAssessments {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly fairnessAssessment: FairnessAssessmentRepository
  ) {}

  async execute(input: ListFairnessAssessmentsInput): Promise<ListFairnessAssessmentsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.frnId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.fairnessAssessment.listFairnessAssessments({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListFairnessAssessmentsOutput;
  }
}
