/**
 * ExecuteCreateFairnessAssessment - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateFairnessAssessment Use Case
 *
 * DDD: Application use case for create FairnessAssessment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateFairnessAssessmentInput, CreateFairnessAssessmentOutput } from "../dto/fairness-assessment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@appetitebind/services/_shared/index.js";
import type { FairnessAssessmentRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateFairnessAssessment {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly fairnessAssessment: FairnessAssessmentRepository
  ) {}

  async execute(input: CreateFairnessAssessmentInput): Promise<CreateFairnessAssessmentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.frnId();

    // All field names extracted from OpenAPI spec: metrics, notes, outcome, vulnerableCustomerConsidered
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.metrics) {
      throw new ValidationError("metrics is required");
    }
    if (!input.outcome) {
      throw new ValidationError("outcome is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (fairness domain)
    const entityId = this.idGenerator.frnId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.fairnessAssessment.createFairnessAssessment({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateFairnessAssessmentOutput;
  }
}
