/**
 * Metric Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { MetricEntity } from "@appetitebind/core/monitoring/models/index.js";
import { monitoringSchemas } from "@appetitebind/core/monitoring";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "mon";

export function createMetric(overrides: Partial<MetricEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    category: overrides.category ?? "technical",
    metricId: overrides.metricId ?? `mtr_${ulid().toLowerCase()}`,
    name: overrides.name ?? faker.person.fullName(),
    useCaseId: overrides.useCaseId ?? `ucs_${ulid().toLowerCase()}`,
    value: overrides.value ?? faker.number.int(),
    ...overrides,
  };

  return monitoringSchemas.MonitoringMetric.parse(raw);
}

export function metricBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createMetric(overrides));
}
