/**
 * ControlTest DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ControlTest DTOs
 *
 * DDD: Application DTOs for ControlTest use cases.
 */

import type { ListAiControlTestsParams, ScheduleAiControlTestRequestInput } from "@appetitebind/core/controls/types";

export type ListAiControlTestsInput = ListAiControlTestsParams;

export type ScheduleAiControlTestInput = ScheduleAiControlTestRequestInput;

export type ListAiControlTestsOutput = {};

export type ScheduleAiControlTestOutput = {};
