/**
 * Evidence DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Evidence DTOs
 *
 * DDD: Application DTOs for Evidence use cases.
 */

import type { SubmitControlTestEvidenceParams, SubmitControlTestEvidenceRequestInput } from "@appetitebind/core/controls/types";

export type SubmitControlTestEvidenceInput = SubmitControlTestEvidenceParams & SubmitControlTestEvidenceRequestInput;

export type SubmitControlTestEvidenceOutput = {};
