/**
 * Execute DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Execute DTOs
 *
 * DDD: Application DTOs for Execute use cases.
 */

import type { ExecuteKillSwitchParams, ExecuteKillSwitchRequestInput } from "@appetitebind/core/controls/types";

export type ExecuteKillSwitchInput = ExecuteKillSwitchParams & ExecuteKillSwitchRequestInput;

export type ExecuteKillSwitchOutput = {};
