/**
 * HandToHumanRule DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HandToHumanRule DTOs
 *
 * DDD: Application DTOs for HandToHumanRule use cases.
 */

import type { ListHandToHumanRulesParams, SetHandToHumanRulesParams, SetHandToHumanRulesRequestInput } from "@appetitebind/core/controls/types";

export type ListHandToHumanRulesInput = ListHandToHumanRulesParams;

export type SetHandToHumanRulesInput = SetHandToHumanRulesParams & SetHandToHumanRulesRequestInput;

export type ListHandToHumanRulesOutput = {};

export type SetHandToHumanRulesOutput = {};
