/**
 * KillSwitch DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * KillSwitch DTOs
 *
 * DDD: Application DTOs for KillSwitch use cases.
 */

import type { GetKillSwitchParams, RegisterKillSwitchParams, RegisterKillSwitchRequestInput } from "@appetitebind/core/controls/types";

export type GetKillSwitchInput = GetKillSwitchParams;

export type RegisterKillSwitchInput = RegisterKillSwitchParams & RegisterKillSwitchRequestInput;

export type GetKillSwitchOutput = {};

export type RegisterKillSwitchOutput = {};
