/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the assessments domain.
 * Use these factories in tests to create test data.
 */

export { createAssessment } from "./assessment/entity/assessment.entity.factory.js";
export { createReferenceComparison } from "./reference-comparison/entity/reference-comparison.entity.factory.js";
export { createRiskIdentification } from "./risk-identification/entity/risk-identification.entity.factory.js";
export { createSignOff } from "./sign-off/entity/sign-off.entity.factory.js";
