/**
 * FairnessAssessmentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FairnessAssessmentRepository Port
 *
 * DDD: Application port for fairnessassessmentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateFairnessAssessmentInput, CreateFairnessAssessmentOutput, ListFairnessAssessmentsInput, ListFairnessAssessmentsOutput } from "../dto/fairness-assessment.dto";
export interface FairnessAssessmentRepository {
  listFairnessAssessments(input: ListFairnessAssessmentsInput): Promise<ListFairnessAssessmentsOutput>;
  createFairnessAssessment(input: CreateFairnessAssessmentInput): Promise<CreateFairnessAssessmentOutput>;
}

export type { CreateFairnessAssessmentInput, CreateFairnessAssessmentOutput, ListFairnessAssessmentsInput, ListFairnessAssessmentsOutput } from "../dto/fairness-assessment.dto";
