/**
 * FairnessPolicyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FairnessPolicyRepository Port
 *
 * DDD: Application port for fairnesspolicyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetFairnessPolicyInput, GetFairnessPolicyOutput, UpdateFairnessPolicyInput, UpdateFairnessPolicyOutput } from "../dto/fairness-policy.dto";
export interface FairnessPolicyRepository {
  getFairnessPolicy(input: GetFairnessPolicyInput): Promise<GetFairnessPolicyOutput>;
  updateFairnessPolicy(input: UpdateFairnessPolicyInput): Promise<UpdateFairnessPolicyOutput>;
}

export type { GetFairnessPolicyInput, GetFairnessPolicyOutput, UpdateFairnessPolicyInput, UpdateFairnessPolicyOutput } from "../dto/fairness-policy.dto";
