/**
 * FairnessPolicy Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/fairness.openapi.types.js";
import { schemas } from "../schemas/fairness.schemas.js";

/**
 * Entity: FairnessPolicyEntity
 * Description: Represents the FairnessPolicy domain model.
 * Source: schemas.FairnessPolicy
 * Type: Persisted Entity (x-dynamodb)
 */
export const FairnessPolicyEntitySchema = schemas.FairnessPolicy;
export type FairnessPolicyEntity = components["schemas"]["FairnessPolicy"];
