/**
 * Repository interface for Owner
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: usecases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  OwnerEntity
} from "../models/owner.entity.js";
import type {
  AssignUseCaseOwnerRequestInput
} from "../types/index.js";
/**
 * OwnerRepository Interface
 */
export interface OwnerRepository extends UpdateReadRepository<OwnerEntity, AssignUseCaseOwnerRequestInput, string, Record<string, never>> {

}
