/**
 * GetKillSwitch DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetKillSwitchParams } from "@appetitebind/core/controls";

export function createGetKillSwitchRequest(overrides: Partial<GetKillSwitchParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
