/**
 * Routes for Owner
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: usecases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { assignUseCaseOwner } from "../handlers/owner.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function ownerRoutes(fastify: FastifyInstance) {
  // PUT /v1/use-cases/{useCaseId}/owner (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/use-cases/:useCaseId/owner",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getUsecasesDependenciesForRequest();
        await assignUseCaseOwner(request, reply, deps);
      });
    }
  );


}
