/**
 * Monitoring Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const ingestMonitoringMetric_Body = z
  .object({
    useCaseId: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
    category: z.enum([
      'technical',
      'business',
      'operational',
      'complaint',
      'data_shift',
    ]),
    name: z.string(),
    value: z.number(),
    threshold: z.number().optional(),
    observedAt: z.string().datetime({ offset: true }).optional(),
  })
  .passthrough();
const ingestComplaintSignal_Body = z
  .object({
    complaintSignalId: z.string().regex(/^cmp_[0-9A-HJKMNP-TV-Z]{26}$/),
    useCaseId: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
    taxonomy: z.enum([
      'discrimination',
      'unfair_outcome',
      'explainability',
      'other_conduct',
    ]),
    externalComplaintId: z.string().optional(),
    receivedAt: z.string().datetime({ offset: true }).optional(),
    createdAt: z.string().datetime({ offset: true }),
    updatedAt: z.string().datetime({ offset: true }),
  })
  .passthrough();
const ingestDataShiftSignal_Body = z
  .object({
    dataShiftSignalId: z.string().regex(/^dst_[0-9A-HJKMNP-TV-Z]{26}$/),
    useCaseId: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
    featureOrSegment: z.string(),
    shiftMagnitude: z.number(),
    detectedAt: z.string().datetime({ offset: true }).optional(),
    createdAt: z.string().datetime({ offset: true }),
    updatedAt: z.string().datetime({ offset: true }),
  })
  .passthrough();

export const schemas: any = {
  ingestMonitoringMetric_Body,
  ingestComplaintSignal_Body,
  ingestDataShiftSignal_Body,
};

const endpoints = makeApi([
  {
    method: 'post',
    path: '/v1/monitoring/complaints',
    alias: 'ingestComplaintSignal',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: ingestComplaintSignal_Body,
      },
    ],
    response: z
      .object({
        data: z
          .object({
            complaintSignalId: z.string().regex(/^cmp_[0-9A-HJKMNP-TV-Z]{26}$/),
            useCaseId: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
            taxonomy: z.enum([
              'discrimination',
              'unfair_outcome',
              'explainability',
              'other_conduct',
            ]),
            externalComplaintId: z.string().optional(),
            receivedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
  {
    method: 'post',
    path: '/v1/monitoring/data-shifts',
    alias: 'ingestDataShiftSignal',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: ingestDataShiftSignal_Body,
      },
    ],
    response: z
      .object({
        data: z
          .object({
            dataShiftSignalId: z.string().regex(/^dst_[0-9A-HJKMNP-TV-Z]{26}$/),
            useCaseId: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
            featureOrSegment: z.string(),
            shiftMagnitude: z.number(),
            detectedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
  {
    method: 'get',
    path: '/v1/monitoring/metrics',
    alias: 'listMonitoringMetrics',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'useCaseId',
        type: 'Query',
        schema: z
          .string()
          .regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/)
          .optional(),
      },
      {
        name: 'category',
        type: 'Query',
        schema: z
          .enum([
            'technical',
            'business',
            'operational',
            'complaint',
            'data_shift',
          ])
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  metricId: z.string().regex(/^mtr_[0-9A-HJKMNP-TV-Z]{26}$/),
                  useCaseId: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
                  category: z.enum([
                    'technical',
                    'business',
                    'operational',
                    'complaint',
                    'data_shift',
                  ]),
                  name: z.string(),
                  value: z.number(),
                  threshold: z.number().optional(),
                  observedAt: z.string().datetime({ offset: true }).optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
  {
    method: 'post',
    path: '/v1/monitoring/metrics',
    alias: 'ingestMonitoringMetric',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: ingestMonitoringMetric_Body,
      },
    ],
    response: z
      .object({
        data: z
          .object({
            metricId: z.string().regex(/^mtr_[0-9A-HJKMNP-TV-Z]{26}$/),
            useCaseId: z.string().regex(/^ucs_[0-9A-HJKMNP-TV-Z]{26}$/),
            category: z.enum([
              'technical',
              'business',
              'operational',
              'complaint',
              'data_shift',
            ]),
            name: z.string(),
            value: z.number(),
            threshold: z.number().optional(),
            observedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
