/**
 * ControlTestRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ControlTestRepository Port
 *
 * DDD: Application port for controltestrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListAiControlTestsInput, ListAiControlTestsOutput, ScheduleAiControlTestInput, ScheduleAiControlTestOutput } from "../dto/control-test.dto";
export interface ControlTestRepository {
  listAiControlTests(input: ListAiControlTestsInput): Promise<ListAiControlTestsOutput>;
  scheduleAiControlTest(input: ScheduleAiControlTestInput): Promise<ScheduleAiControlTestOutput>;
}

export type { ListAiControlTestsInput, ListAiControlTestsOutput, ScheduleAiControlTestInput, ScheduleAiControlTestOutput } from "../dto/control-test.dto";
