/**
 * HandToHumanRuleRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HandToHumanRuleRepository Port
 *
 * DDD: Application port for handtohumanrulerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListHandToHumanRulesInput, ListHandToHumanRulesOutput, SetHandToHumanRulesInput, SetHandToHumanRulesOutput } from "../dto/hand-to-human-rule.dto";
export interface HandToHumanRuleRepository {
  listHandToHumanRules(input: ListHandToHumanRulesInput): Promise<ListHandToHumanRulesOutput>;
  setHandToHumanRules(input: SetHandToHumanRulesInput): Promise<SetHandToHumanRulesOutput>;
}

export type { ListHandToHumanRulesInput, ListHandToHumanRulesOutput, SetHandToHumanRulesInput, SetHandToHumanRulesOutput } from "../dto/hand-to-human-rule.dto";
