/**
 * KillSwitchRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * KillSwitchRepository Port
 *
 * DDD: Application port for killswitchrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetKillSwitchInput, GetKillSwitchOutput, RegisterKillSwitchInput, RegisterKillSwitchOutput } from "../dto/kill-switch.dto";
export interface KillSwitchRepository {
  getKillSwitch(input: GetKillSwitchInput): Promise<GetKillSwitchOutput>;
  registerKillSwitch(input: RegisterKillSwitchInput): Promise<RegisterKillSwitchOutput>;
}

export type { GetKillSwitchInput, GetKillSwitchOutput, RegisterKillSwitchInput, RegisterKillSwitchOutput } from "../dto/kill-switch.dto";
