/**
 * AppetiteCriteriumRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appetite
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AppetiteCriteriumRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AppetiteCriteriumRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AppetiteCriteriumRepository,
} from "@appetitebind/services/appetite";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AppetiteCriteriumRepositoryDdb } from "./appetite-criterium-repository.ddb.js";

/**
 * AppetiteCriteriumRepositoryAdapter
 *
 * Implements AppetiteCriteriumRepository port for infrastructure layer.
 */
export class AppetiteCriteriumRepositoryAdapter implements AppetiteCriteriumRepository {
  private readonly ddb: AppetiteCriteriumRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AppetiteCriteriumRepositoryDdb(this.dynamoClient);
  }

  async getAppetiteCriteria(input: Parameters<AppetiteCriteriumRepository['getAppetiteCriteria']>[0]): Promise<Awaited<ReturnType<AppetiteCriteriumRepository['getAppetiteCriteria']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAppetiteCriteria(input);
  }

  async updateAppetiteCriteria(input: Parameters<AppetiteCriteriumRepository['updateAppetiteCriteria']>[0]): Promise<Awaited<ReturnType<AppetiteCriteriumRepository['updateAppetiteCriteria']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateAppetiteCriteria(input);
  }
}
