/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appetite
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./appetite-binding-repository.ddb.js";
export * from "./appetite-criterium-repository.ddb.js";
export * from "./appetite-binding-repository.adapter.js";
export * from "./appetite-criterium-repository.adapter.js";
