/**
 * FairnessAssessmentRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FairnessAssessmentRepositoryDdb
 *
 * DDD: Infrastructure adapter implementing FairnessAssessment repository using DynamoDB.
 * Generated from x-dynamodb metadata in OpenAPI schema.
 */

import type { FairnessAssessmentRepository } from "@appetitebind/services/fairness";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { getCoreTableName, getBaseTableName, getAnalyticsTableName } from "../_shared/dynamodb-utils.js";
import { sanitizeItem } from "../_shared/dynamodb-key-helpers.js";
import { ulid } from "ulid";

/**
 * FairnessAssessmentRepositoryDdb using DynamoDB table (type: core)
 *
 * Entity Type: FAIRNESS_ASSESSMENT
 * Entity Token: FAIRNESS_ASSESSMENT
 * SK Prefix: FAIRNESS_ASSESSMENT
 */
export class FairnessAssessmentRepositoryDdb implements FairnessAssessmentRepository {
  private readonly TABLE_NAME: string;
  // Metadata from x-dynamodb annotation - all values are dynamic
  private readonly ENTITY_TYPE = "FAIRNESS_ASSESSMENT";
  private readonly ENTITY_TOKEN = "FAIRNESS_ASSESSMENT";
  private readonly SK_PREFIX = "FAIRNESS_ASSESSMENT";
  private readonly IS_CHILD_ENTITY = false;
  private readonly CREATED_AT_FIELD = "createdAt";
  private readonly UPDATED_AT_FIELD = "updatedAt";
  private readonly SOFT_DELETE_ENABLED = false;
  private readonly DOMAIN = "FAIRNESS";
  private readonly ENTITY_TYPE_PK = "FAIRNESS_ASSESSMENTS";
  private generateCorrelationId(): string {
    const domainPrefix = "frn";
    return `${domainPrefix}_${ulid().toLowerCase()}`;
  }
  /** Partition key from x-dynamodb: ORG#orgId#DOMAIN#COLLECTION#entityId (id in PK). */
  private buildPK(orgId: string, entityId: string): string {
    return `ORG#${orgId}#${this.DOMAIN}#${this.ENTITY_TYPE_PK}#${entityId}`;
  }
  /** Collection prefix for list/query: ORG#orgId#DOMAIN#COLLECTION (no entityId). */
  private getCollectionPK(orgId: string): string {
    return `ORG#${orgId}#${this.DOMAIN}#${this.ENTITY_TYPE_PK}`;
  }
  /** Deterministic SK: ENTITY#entityId (legacy …#TIMESTAMP#ts dual-read via begins_with). */
  private buildSK(entityId: string, _identifier?: string): string {
    return `${this.ENTITY_TOKEN}#${entityId}`;
  }
  /** GSI time SK: updatedAt#entityId (uniqueness under bulk writes). */
  private buildGsiSK(updatedAt: string, entityId: string): string {
    return `${updatedAt}#${entityId}`;
  }
  /** GSI2 list-by-org: ORG#orgId#COLLECTION */
  private buildGSI2PK(orgId: string): string {
    return `ORG#${orgId}#${this.ENTITY_TYPE_PK}`;
  }


  constructor(private readonly dynamoClient: AdapterDynamoDBClient) {
    const tableTypeFromMetadata = "core";
    const tableTypeMap = {
      core: getCoreTableName,
      base: getBaseTableName,
      analytics: getAnalyticsTableName,
    };
    const tableNameFn = tableTypeMap[tableTypeFromMetadata] || getCoreTableName;
    this.TABLE_NAME = tableNameFn();
  }

  async listFairnessAssessments(input: Parameters<FairnessAssessmentRepository['listFairnessAssessments']>[0]): Promise<Awaited<ReturnType<FairnessAssessmentRepository['listFairnessAssessments']>>> {
    const inputExt = input as Record<string, unknown>;

    if (!input) {
      throw new Error("Missing required parameter: input");
    }
    if (!inputExt.orgId) {
      throw new Error("Missing required parameter: orgId");
    }
    const prefix = this.getCollectionPK(inputExt.orgId as string);
    const rawLimit = inputExt?.limit;
    const parsedLimit = rawLimit == null || rawLimit === ""
      ? 50
      : (typeof rawLimit === "string" ? parseInt(rawLimit as string, 10) : Number(rawLimit));
    const limit = Number.isFinite(parsedLimit) && parsedLimit > 0 ? parsedLimit : 50;
    const result = await this.dynamoClient.scan({
      TableName: this.TABLE_NAME,
      FilterExpression: "begins_with(PK, :prefix)",
      ExpressionAttributeValues: { ":prefix": prefix },
      Limit: limit,
      ...((() => {
        const c = inputExt?.cursor;
        if (!c || (typeof c === "string" && !c.trim())) return {};
        try {
          return {
            ExclusiveStartKey: typeof c === "string"
              ? JSON.parse(Buffer.from(c, "base64").toString())
              : c,
          };
        } catch {
          return {};
        }
      })()),
    });
    const items = ((result.Items || []) as Record<string, unknown>[]).map((i) => sanitizeItem(i));
    return {
      data: { items: items } as unknown as any,
      meta: {
        correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
        timestamp: new Date().toISOString(),
        pagination: {
          nextCursor: result.LastEvaluatedKey ? Buffer.from(JSON.stringify(result.LastEvaluatedKey)).toString("base64") : null,
          prevCursor: null,
          limit: inputExt?.limit || 50,
        },
      } as unknown as any,
    };
  }

  async createFairnessAssessment(input: Parameters<FairnessAssessmentRepository['createFairnessAssessment']>[0]): Promise<Awaited<ReturnType<FairnessAssessmentRepository['createFairnessAssessment']>>> {
    const inputExt = input as Record<string, unknown>;

    const now = new Date().toISOString();
    const orgId = inputExt.orgId;
    const fairnessAssessmentId = inputExt?.fairnessAssessmentId ?? inputExt?.id;
    if (!fairnessAssessmentId) throw new Error("Missing required parameter: fairnessAssessmentId (inject from use case)");
    const pk = this.buildPK(orgId as string, fairnessAssessmentId as string);
    const sk = this.buildSK(fairnessAssessmentId as string);
    const excludedFields = ["fairnessAssessmentId" as string, "id"];
    const inputWithoutId = Object.fromEntries(
      Object.entries(input || {}).filter(([key]) => !excludedFields.includes(key))
    );
    const item = {
      ...inputWithoutId,
      fairnessAssessmentId: fairnessAssessmentId,
      PK: pk,
      SK: sk,
      entityType: this.ENTITY_TYPE,
      [this.CREATED_AT_FIELD]: now,
      [this.UPDATED_AT_FIELD]: now,
    };
    await this.dynamoClient.put({
      TableName: this.TABLE_NAME,
      Item: item,
      ConditionExpression: "attribute_not_exists(PK) AND attribute_not_exists(SK)",
    });
    return {
      data: sanitizeItem(item as Record<string, unknown>) as unknown as any,
      meta: {
        correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
        timestamp: new Date().toISOString(),
      } as unknown as any,
    };
  }
}
