/**
 * FairnessAssessmentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FairnessAssessmentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements FairnessAssessmentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  FairnessAssessmentRepository,
} from "@appetitebind/services/fairness";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { FairnessAssessmentRepositoryDdb } from "./fairness-assessment-repository.ddb.js";

/**
 * FairnessAssessmentRepositoryAdapter
 *
 * Implements FairnessAssessmentRepository port for infrastructure layer.
 */
export class FairnessAssessmentRepositoryAdapter implements FairnessAssessmentRepository {
  private readonly ddb: FairnessAssessmentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new FairnessAssessmentRepositoryDdb(this.dynamoClient);
  }

  async listFairnessAssessments(input: Parameters<FairnessAssessmentRepository['listFairnessAssessments']>[0]): Promise<Awaited<ReturnType<FairnessAssessmentRepository['listFairnessAssessments']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listFairnessAssessments(input);
  }

  async createFairnessAssessment(input: Parameters<FairnessAssessmentRepository['createFairnessAssessment']>[0]): Promise<Awaited<ReturnType<FairnessAssessmentRepository['createFairnessAssessment']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createFairnessAssessment(input);
  }
}
