/**
 * FairnessPolicyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fairness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FairnessPolicyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements FairnessPolicyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  FairnessPolicyRepository,
} from "@appetitebind/services/fairness";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { FairnessPolicyRepositoryDdb } from "./fairness-policy-repository.ddb.js";

/**
 * FairnessPolicyRepositoryAdapter
 *
 * Implements FairnessPolicyRepository port for infrastructure layer.
 */
export class FairnessPolicyRepositoryAdapter implements FairnessPolicyRepository {
  private readonly ddb: FairnessPolicyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new FairnessPolicyRepositoryDdb(this.dynamoClient);
  }

  async getFairnessPolicy(input: Parameters<FairnessPolicyRepository['getFairnessPolicy']>[0]): Promise<Awaited<ReturnType<FairnessPolicyRepository['getFairnessPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getFairnessPolicy(input);
  }

  async updateFairnessPolicy(input: Parameters<FairnessPolicyRepository['updateFairnessPolicy']>[0]): Promise<Awaited<ReturnType<FairnessPolicyRepository['updateFairnessPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateFairnessPolicy(input);
  }
}
