/**
 * ControlTest Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/controls.openapi.types.js";
import { schemas } from "../schemas/controls.schemas.js";

/**
 * Entity: ControlTestEntity
 * Description: Represents the ControlTest domain model.
 * Source: schemas.AiControlTest
 * Type: Persisted Entity (x-dynamodb)
 */
export const ControlTestEntitySchema = schemas.AiControlTest;
export type ControlTestEntity = components["schemas"]["AiControlTest"];
