/**
 * Drill Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/controls.openapi.types.js";
import { schemas } from "../schemas/controls.schemas.js";

/**
 * Entity: DrillEntity
 * Description: Represents the Drill domain model.
 * Source: schemas.KillSwitchDrill
 * Type: Persisted Entity (x-dynamodb)
 */
export const DrillEntitySchema = schemas.KillSwitchDrill;
export type DrillEntity = components["schemas"]["KillSwitchDrill"];
