/**
 * HandToHumanRule Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/controls.openapi.types.js";
import { schemas } from "../schemas/controls.schemas.js";

/**
 * Entity: HandToHumanRuleEntity
 * Description: Represents the HandToHumanRule domain model.
 * Source: schemas.HandToHumanRule
 * Type: Persisted Entity (x-dynamodb)
 */
export const HandToHumanRuleEntitySchema = schemas.HandToHumanRule;
export type HandToHumanRuleEntity = components["schemas"]["HandToHumanRule"];
