/**
 * SupervisoryExportRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SupervisoryExportRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SupervisoryExportRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SupervisoryExportRepository,
} from "@appetitebind/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SupervisoryExportRepositoryDdb } from "./supervisory-export-repository.ddb.js";

/**
 * SupervisoryExportRepositoryAdapter
 *
 * Implements SupervisoryExportRepository port for infrastructure layer.
 */
export class SupervisoryExportRepositoryAdapter implements SupervisoryExportRepository {
  private readonly ddb: SupervisoryExportRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SupervisoryExportRepositoryDdb(this.dynamoClient);
  }

  async createSupervisoryExport(input: Parameters<SupervisoryExportRepository['createSupervisoryExport']>[0]): Promise<Awaited<ReturnType<SupervisoryExportRepository['createSupervisoryExport']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createSupervisoryExport(input);
  }
}
