/**
 * SupervisoryExportRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SupervisoryExportRepositoryDdb
 *
 * DDD: Infrastructure adapter implementing SupervisoryExport repository using DynamoDB.
 * Generated from x-dynamodb metadata in OpenAPI schema.
 */

import type { SupervisoryExportRepository } from "@appetitebind/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { getCoreTableName, getBaseTableName, getAnalyticsTableName } from "../_shared/dynamodb-utils.js";
import { sanitizeItem } from "../_shared/dynamodb-key-helpers.js";
import { ulid } from "ulid";

/**
 * SupervisoryExportRepositoryDdb using DynamoDB table (type: core)
 *
 * Entity Type: SUPERVISORY_EXPORT
 * Entity Token: SUPERVISORY_EXPORT
 * SK Prefix: SUPERVISORY_EXPORT
 */
export class SupervisoryExportRepositoryDdb implements SupervisoryExportRepository {
  private readonly TABLE_NAME: string;
  // Metadata from x-dynamodb annotation - all values are dynamic
  private readonly ENTITY_TYPE = "SUPERVISORY_EXPORT";
  private readonly ENTITY_TOKEN = "SUPERVISORY_EXPORT";
  private readonly SK_PREFIX = "SUPERVISORY_EXPORT";
  private readonly IS_CHILD_ENTITY = false;
  private readonly CREATED_AT_FIELD = "createdAt";
  private readonly UPDATED_AT_FIELD = "updatedAt";
  private readonly SOFT_DELETE_ENABLED = false;
  private readonly DOMAIN = "GOVERNANCE";
  private readonly ENTITY_TYPE_PK = "SUPERVISORY_EXPORTS";
  private generateCorrelationId(): string {
    const domainPrefix = "gov";
    return `${domainPrefix}_${ulid().toLowerCase()}`;
  }
  /** Partition key from x-dynamodb: ORG#orgId#DOMAIN#COLLECTION#entityId (id in PK). */
  private buildPK(orgId: string, entityId: string): string {
    return `ORG#${orgId}#${this.DOMAIN}#${this.ENTITY_TYPE_PK}#${entityId}`;
  }
  /** Collection prefix for list/query: ORG#orgId#DOMAIN#COLLECTION (no entityId). */
  private getCollectionPK(orgId: string): string {
    return `ORG#${orgId}#${this.DOMAIN}#${this.ENTITY_TYPE_PK}`;
  }
  /** Deterministic SK: ENTITY#entityId (legacy …#TIMESTAMP#ts dual-read via begins_with). */
  private buildSK(entityId: string, _identifier?: string): string {
    return `${this.ENTITY_TOKEN}#${entityId}`;
  }
  /** GSI time SK: updatedAt#entityId (uniqueness under bulk writes). */
  private buildGsiSK(updatedAt: string, entityId: string): string {
    return `${updatedAt}#${entityId}`;
  }
  /** GSI2 list-by-org: ORG#orgId#COLLECTION */
  private buildGSI2PK(orgId: string): string {
    return `ORG#${orgId}#${this.ENTITY_TYPE_PK}`;
  }


  constructor(private readonly dynamoClient: AdapterDynamoDBClient) {
    const tableTypeFromMetadata = "core";
    const tableTypeMap = {
      core: getCoreTableName,
      base: getBaseTableName,
      analytics: getAnalyticsTableName,
    };
    const tableNameFn = tableTypeMap[tableTypeFromMetadata] || getCoreTableName;
    this.TABLE_NAME = tableNameFn();
  }

  async createSupervisoryExport(input: Parameters<SupervisoryExportRepository['createSupervisoryExport']>[0]): Promise<Awaited<ReturnType<SupervisoryExportRepository['createSupervisoryExport']>>> {
    const inputExt = input as Record<string, unknown>;

    const now = new Date().toISOString();
    const orgId = inputExt.orgId;
    const supervisoryExportId = inputExt?.supervisoryExportId ?? inputExt?.id;
    if (!supervisoryExportId) throw new Error("Missing required parameter: supervisoryExportId (inject from use case)");
    const pk = this.buildPK(orgId as string, supervisoryExportId as string);
    const sk = this.buildSK(supervisoryExportId as string);
    const excludedFields = ["supervisoryExportId" as string, "id"];
    const inputWithoutId = Object.fromEntries(
      Object.entries(input || {}).filter(([key]) => !excludedFields.includes(key))
    );
    const item = {
      ...inputWithoutId,
      supervisoryExportId: supervisoryExportId,
      PK: pk,
      SK: sk,
      entityType: this.ENTITY_TYPE,
      [this.CREATED_AT_FIELD]: now,
      [this.UPDATED_AT_FIELD]: now,
    };
    await this.dynamoClient.put({
      TableName: this.TABLE_NAME,
      Item: item,
      ConditionExpression: "attribute_not_exists(PK) AND attribute_not_exists(SK)",
    });
    return {
      data: sanitizeItem(item as Record<string, unknown>) as unknown as any,
      meta: {
        correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
        timestamp: new Date().toISOString(),
      } as unknown as any,
    };
  }
}
