/**
 * VariationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VariationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements VariationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  VariationRepository,
} from "@appetitebind/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { VariationRepositoryDdb } from "./variation-repository.ddb.js";

/**
 * VariationRepositoryAdapter
 *
 * Implements VariationRepository port for infrastructure layer.
 */
export class VariationRepositoryAdapter implements VariationRepository {
  private readonly ddb: VariationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new VariationRepositoryDdb(this.dynamoClient);
  }

  async listAlgorithmVariations(input: Parameters<VariationRepository['listAlgorithmVariations']>[0]): Promise<Awaited<ReturnType<VariationRepository['listAlgorithmVariations']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAlgorithmVariations(input);
  }

  async recordAlgorithmVariation(input: Parameters<VariationRepository['recordAlgorithmVariation']>[0]): Promise<Awaited<ReturnType<VariationRepository['recordAlgorithmVariation']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.recordAlgorithmVariation(input);
  }
}
