/**
 * Drill Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { DrillEntity } from "@appetitebind/core/controls/models/index.js";
import { controlsSchemas } from "@appetitebind/core/controls";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ctl";

export function createDrill(overrides: Partial<DrillEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    drilledAt: overrides.drilledAt ?? new Date().toISOString(),
    executedBy: overrides.executedBy ?? faker.lorem.word(),
    killSwitchDrillId: overrides.killSwitchDrillId ?? `ksd_${ulid().toLowerCase()}`,
    useCaseId: overrides.useCaseId ?? `ucs_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return controlsSchemas.KillSwitchDrill.parse(raw);
}

export function drillBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createDrill(overrides));
}
