/**
 * Repository interface for AppetiteBinding
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: appetite
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AppetiteBindingEntity
} from "../models/appetite-binding.entity.js";
import type {
  AppetiteBinding
} from "../types/index.js";
/**
 * AppetiteBindingRepository Interface
 */
export interface AppetiteBindingRepository extends CreateReadRepository<AppetiteBindingEntity, AppetiteBinding, string, Record<string, never>> {

}
